package com.wenzai.neosim.datagen;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.wenzai.neosim.NeoSim;
import com.wenzai.neosim.block.ModBlocks;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Map;

public class LangZhCn extends LanguageProvider
{
	public LangZhCn(PackOutput output)
	{
		super(output, NeoSim.MOD_ID, "zh_cn");
	}

	@Override
	protected void addTranslations()
	{
		add(ModBlocks.BUILDING_CONSTRUCTOR.get(), "建筑模盒");
		add(ModBlocks.CONTROL_BOX.get(), "控制箱");
		add(ModBlocks.MARKER.get(), "标记棒");
		add(ModBlocks.FARMING_BOX.get(), "农业盒");
		add(ModBlocks.MINING_BOX.get(), "矿业盒");
		add(ModBlocks.DELIVERY_BOX.get(), "快递盒");
		add(ModBlocks.REBUILD_BOX.get(), "重建模盒");
		add(ModBlocks.LIVING_POINT.get(), "生活点");

		add("gui.neosim.DeliveryBox.title","快递盒");
		add("gui.neosim.DeliveryBox.worker","快递员：%s");
		add("gui.neosim.DeliveryBox.workerNone","暂无快递员");
		add("gui.neosim.DeliveryBox.workerLevel","快递员等级：%s");
		add("gui.neosim.DeliveryBox.hire","雇佣");
		add("gui.neosim.DeliveryBox.fire","解雇");
		add("gui.neosim.DeliveryBox.pause","暂停");
		add("gui.neosim.DeliveryBox.resume","继续");
		add("gui.neosim.DeliveryBox.close","关闭");
		add("gui.neosim.DeliveryBox.hireTitle","选择快递员");
		add("gui.neosim.DeliveryBox.goBack","返回");
		add("gui.neosim.DeliveryBox.state","状态：%s");
		add("gui.neosim.DeliveryBox.state.idle","待命");
		add("gui.neosim.DeliveryBox.state.waitingWorker","等待快递员");
		add("gui.neosim.DeliveryBox.state.workerAssigned","快递员就位");
		add("gui.neosim.DeliveryBox.state.walking","配送中");
		add("gui.neosim.DeliveryBox.state.depositing","投料中");
		add("gui.neosim.DeliveryBox.state.returning","返回站点");
		add("gui.neosim.DeliveryBox.station","快递站材料");
		add("gui.neosim.DeliveryBox.station.title","快递站材料");
		add("gui.neosim.DeliveryBox.station.header","已读取 %s 个箱子 · %s 种材料");
		add("gui.neosim.DeliveryBox.station.scanning","读取中…");
		add("gui.neosim.DeliveryBox.station.timeout","读取超时，请再点一次刷新");
		add("gui.neosim.DeliveryBox.station.empty","箱子里没有物品");
		add("gui.neosim.DeliveryBox.station.page","第 %s/%s 页");
		add("gui.neosim.DeliveryBox.station.refresh","刷新");
		add("gui.neosim.DeliveryBox.prev","上一页");
		add("gui.neosim.DeliveryBox.next","下一页");


		// 城市信息 GUI（I 键唯一入口）
		add("key.categories.neo_sim","新模拟城市");
		add("key.neosim.cityinfo","城市信息");
		add("gui.neosim.cityinfo.title","城市信息");
		add("gui.neosim.cityinfo.tab.overview","概览");
		add("gui.neosim.cityinfo.tab.residents","居民");
		add("gui.neosim.cityinfo.tab.buildings","建筑");
		add("gui.neosim.cityinfo.tab.config","配置");
		add("gui.neosim.cityinfo.tab.convert","转换");

		// 转换页（.txt → .litematic）
		add("gui.neosim.cityinfo.convert.dir","目录：%s");
		add("gui.neosim.cityinfo.convert.hint","列出自定义目录下还没转换的 .txt；旁边已有同名 .litematic 的会自动隐藏");
		add("gui.neosim.cityinfo.convert.empty","这个目录里没有待转换的 .txt 蓝图");
		add("gui.neosim.cityinfo.convert.row","%s · %s · %s · %s");
		add("gui.neosim.cityinfo.convert.authorNone","无作者");
		add("gui.neosim.cityinfo.convert.info","选中：%s（%s · %s · %s）");
		add("gui.neosim.cityinfo.convert.author","作者");
		add("gui.neosim.cityinfo.convert.authorHint","作者名写进 Metadata.Author；清空则用文件里的 AU=，都没有就是 Unknown。「全部转换」始终用各自的 AU=");
		add("gui.neosim.cityinfo.convert.convertSelected","转换选中");
		add("gui.neosim.cityinfo.convert.convertAll","全部转换");
		add("gui.neosim.cityinfo.convert.openFolder","打开文件夹");
		add("gui.neosim.cityinfo.convert.rescan","刷新");
		add("gui.neosim.cityinfo.convert.prevPage","上一页");
		add("gui.neosim.cityinfo.convert.nextPage","下一页");
		add("gui.neosim.cityinfo.convert.pageInfo","第 %s/%s 页 · 共 %s 份");
		add("gui.neosim.cityinfo.convert.progress","转换中 %s/%s…");
		add("gui.neosim.cityinfo.convert.done","转换完成：成功 %s 份（作者名已写入 Metadata.Author）");
		add("gui.neosim.cityinfo.convert.doneWithErrors","转换完成：成功 %s 份，失败 %s 份 — %s");
		add("gui.neosim.cityinfo.convert.openFailed","打开目录失败：%s");
		add("gui.neosim.cityinfo.close","关闭");
		add("gui.neosim.cityinfo.prevPage","上一页");
		add("gui.neosim.cityinfo.nextPage","下一页");
		add("gui.neosim.cityinfo.pageInfo","第 %s/%s 页 · 共 %s 条");
		add("gui.neosim.cityinfo.noCity","尚未加入城市（配置页仍可用）");
		add("gui.neosim.cityinfo.mode.none","未选择");
		add("gui.neosim.cityinfo.overview.city","城市：%s");
		add("gui.neosim.cityinfo.overview.time","时间：%s");
		add("gui.neosim.cityinfo.overview.weekday","星期：%s");
		add("gui.neosim.cityinfo.overview.day","天数：%s");
		add("gui.neosim.cityinfo.overview.population","人口：%s");
		add("gui.neosim.cityinfo.overview.credit","资金：%s");
		add("gui.neosim.cityinfo.overview.mode","模式：%s");
		add("gui.neosim.cityinfo.overview.populationMax","人口上限：%s");
		add("gui.neosim.cityinfo.overview.buildings","控制箱记录：%s");
		add("gui.neosim.cityinfo.overview.homeless","无家市民：%s");
		add("gui.neosim.cityinfo.resident.row","%s - %s");
		add("gui.neosim.cityinfo.resident.homelessTag","无家");
		add("gui.neosim.cityinfo.resident.none","暂无居民记录");
		add("gui.neosim.cityinfo.building.row","%s - %s");
		add("gui.neosim.cityinfo.building.vacant","空余");
		add("gui.neosim.cityinfo.building.none","该类型暂无建筑记录");
		add("gui.neosim.cityinfo.type.residential","住宅");
		add("gui.neosim.cityinfo.type.commercial","商业");
		add("gui.neosim.cityinfo.type.industrial","工业");
		add("gui.neosim.cityinfo.type.other","其他");
		add("gui.neosim.cityinfo.type.count","%s (%s)");

		// 配置中心
		add("gui.neosim.config.category.compat","兼容");
		add("gui.neosim.config.category.building","建造");
		add("gui.neosim.config.category.work","工作");
		add("gui.neosim.config.category.mapping","映射");
		add("gui.neosim.config.category.ui","界面");
		add("gui.neosim.config.category.notOpen","该分类尚未开放管理");
		add("gui.neosim.config.category.plan","计划中的文件：%s");
		add("gui.neosim.config.pickCategory","请选择一个分类");
		add("gui.neosim.config.status","已加载 外部 %s 条 · 内置 %s 条 · 类型规则 %s 条 · 依附方块 %s 个");
		add("gui.neosim.config.errorHint","有解析错误，见 NeoSim/Json/_state/errors.txt");
		add("gui.neosim.config.pageInfo","第 %s/%s 页 · 共 %s 条");
		add("gui.neosim.config.unsaved","未保存");
		add("gui.neosim.config.search","搜索注册名/类型");
		add("gui.neosim.config.filter.all","筛选：全部");
		add("gui.neosim.config.filter.attached","筛选：仅依附");
		add("gui.neosim.config.filter.solid","筛选：仅非依附");
		add("gui.neosim.config.detail.none","选中一条规则查看详情");
		add("gui.neosim.config.detail.mode","模式：%s");
		add("gui.neosim.config.detail.phase","轮次：%s");
		add("gui.neosim.config.detail.source","来源：%s");
		add("gui.neosim.config.detail.typeRule","内置类型规则（只读，可被外部规则覆盖）");
		add("gui.neosim.config.detail.rule","外部规则 #%s");
		add("gui.neosim.config.source.external","外部");
		add("gui.neosim.config.source.builtin","内置");
		add("gui.neosim.config.state.on","状态：启用");
		add("gui.neosim.config.state.off","状态：已停用");
		add("gui.neosim.config.phase.1","第一轮（实心）");
		add("gui.neosim.config.phase.2","第二轮（依附）");
		add("gui.neosim.config.mode.auto","自动");
		add("gui.neosim.config.mode.none","非依附");
		add("gui.neosim.config.mode.any","任意依附");
		add("gui.neosim.config.mode.wall","贴墙");
		add("gui.neosim.config.mode.ground","地面");
		add("gui.neosim.config.mode.ceiling","悬挂");
		add("gui.neosim.config.addHeld","加入手持方块");
		add("gui.neosim.config.cycleMode","切换模式");
		add("gui.neosim.config.disable","停用");
		add("gui.neosim.config.enable","启用");
		add("gui.neosim.config.remove","删除");
		add("gui.neosim.config.save","保存");
		add("gui.neosim.config.reload","重载");
		add("gui.neosim.config.prevPage","上一页");
		add("gui.neosim.config.nextPage","下一页");
		add("gui.neosim.config.saved","已保存并生效");
		add("gui.neosim.config.saveFailed","保存失败（无写权限？）");
		add("gui.neosim.config.reloaded","已从文件重载");
		add("gui.neosim.config.added","已加入 %s（记得保存）");
		add("gui.neosim.config.alreadyAdded","%s 已在表中");
		add("gui.neosim.config.file.attached","依附方块表");
		add("gui.neosim.config.file.crops","模组作物表");
		add("gui.neosim.config.status.attached","已加载 外部 %s 条 · 内置 %s 条 · 依附方块 %s 个");
		add("gui.neosim.config.status.crops","已检测模组作物 %s 种 · 生效 %s 种 · 外部规则 %s 条 · 内置规则 %s 条");
		add("gui.neosim.config.status.modded","模组方块 %s 个（%s 个模组）· 其中依赖性 %s 个排第二轮 · 已排除 %s 个");
		add("gui.neosim.config.detail.detected","自动检测（模组扫描）");
		add("gui.neosim.config.detail.detectedRule","自动检测（模组扫描） · 外部规则 #%s");
		add("gui.neosim.config.crop.water","需水");
		add("gui.neosim.config.crop.noWater","不需水");
		add("gui.neosim.config.crop.excluded","已排除");
		add("gui.neosim.config.crop.mature","成熟目标 %s");
		add("gui.neosim.config.needsWater","需水");
		add("gui.neosim.config.exclude","排除");
		add("gui.neosim.config.unexclude","取消排除");
		add("gui.neosim.config.rescan","重新扫描");
		add("gui.neosim.config.rescanned","已重新扫描：检测到 %s 种模组作物");
		add("gui.neosim.config.fileComment.attached","依附方块表：外部覆盖内置。attach 取值 wall 贴墙 / ground 地面 / ceiling 悬挂 / any 只延后 / none 不是依附性方块 / auto 交给 canSurvive 兜底。");
		add("gui.neosim.config.fileComment.crops","模组作物表覆盖规则：mature 成熟目标 / needsWater 需水 / excluded 排除 / enabled 停用。detected 段由模组自动扫描写入。");

		// 界面（个人外观设置：HUD / 投影）
		add("gui.neosim.ui.tab.hud","HUD 外观");
		add("gui.neosim.ui.tab.content","HUD 内容");
		add("gui.neosim.ui.tab.preview","投影预览");
		add("gui.neosim.ui.status.crowded","窗口太矮，部分设置没显示：把窗口拉高或降低 GUI 缩放");
		add("gui.neosim.ui.on","开");
		add("gui.neosim.ui.off","关");
		add("gui.neosim.ui.row.anchor","位置");
		add("gui.neosim.ui.row.offset","偏移");
		add("gui.neosim.ui.row.scale","大小");
		add("gui.neosim.ui.row.color","文字颜色");
		add("gui.neosim.ui.row.layout","排版");
		add("gui.neosim.ui.row.block","阴影与背景");
		add("gui.neosim.ui.row.tint","投影颜色");
		add("gui.neosim.ui.row.alpha","不透明度");
		add("gui.neosim.ui.row.mix","方块纹理显示度");
		add("gui.neosim.ui.layout.single","单行");
		add("gui.neosim.ui.layout.multi","多行");
		add("gui.neosim.ui.anchor.top_left","左上");
		add("gui.neosim.ui.anchor.top_center","上中");
		add("gui.neosim.ui.anchor.top_right","右上");
		add("gui.neosim.ui.anchor.middle_left","左中");
		add("gui.neosim.ui.anchor.middle_center","正中");
		add("gui.neosim.ui.anchor.middle_right","右中");
		add("gui.neosim.ui.anchor.bottom_left","左下");
		add("gui.neosim.ui.anchor.bottom_center","下中");
		add("gui.neosim.ui.anchor.bottom_right","右下");
		add("gui.neosim.ui.separator.0","短横 (“ - ”)");
		add("gui.neosim.ui.separator.1","竖线 (“ | ”)");
		add("gui.neosim.ui.separator.2","空格");
		add("gui.neosim.ui.separator.3","中点 (“ · ”)");
		add("gui.neosim.ui.field.city","城市");
		add("gui.neosim.ui.field.time","时间");
		add("gui.neosim.ui.field.weekday","星期");
		add("gui.neosim.ui.field.day","天数");
		add("gui.neosim.ui.field.population","人口");
		add("gui.neosim.ui.field.credit","资金");
		add("gui.neosim.ui.field.mode","模式");
		add("gui.neosim.ui.preview.hint2","纹理显示度越低，树叶这类镂空方块越接近实心");
		add("gui.neosim.ui.save","保存");
		add("gui.neosim.ui.reload","重载");
		add("gui.neosim.ui.reset.page","重置");
		add("gui.neosim.ui.row.hud","HUD显示");
		add("gui.neosim.ui.row.shadow","阴影显示");
		add("gui.neosim.ui.preset","预设");
		add("gui.neosim.ui.status.other","另一页还有未保存的改动");
		add("gui.neosim.ui.confirm","确认重置？");
		add("gui.neosim.ui.saved","已保存");
		add("gui.neosim.ui.saveFailed","保存失败，见 NeoSim/Json/_state/errors.txt");
		add("gui.neosim.ui.reloaded","已重新读取文件");
		add("gui.neosim.ui.resetPage","本页已恢复默认（原文件已备份为 .bak）");
		add("gui.neosim.ui.status.unsaved","有未保存的改动");
		add("gui.neosim.ui.status.saved","已与文件一致");
		add("config.neosim.hideHudInGui","打开界面时隐藏 HUD");
		add("config.neosim.viewDistance","服务端视距（0=关闭，沿用 server.properties）");
		add("config.neosim.simulationDistance","服务端模拟距离（0=关闭，沿用 server.properties）");

		add("config.neosim.deliveryCreditPerUnit","每件材料送达扣款");
		add("config.neosim.deliveryChunkRadius","快递员区块窗口半径");
		add("config.neosim.workboxEnabled","快递盒 / 重建模盒 总开关");
		add("config.neosim.rebuildPerTick","重建模盒：每 tick 处理上限");
		add("config.neosim.rebuildMaxChunks","重建模盒：强制加载区块上限");
		add("config.neosim.rebuildCreditPerBlock","重建模盒：每补一块扣款");
		add("neo_sim.configuration.workbox","工作盒总开关");
		add("neo_sim.configuration.workbox.button","工作盒总开关");
		add("neo_sim.configuration.workbox.tooltip","同时开启/关闭快递盒与重建模盒");
		add("neo_sim.configuration.delivery","快递盒");
		add("neo_sim.configuration.delivery.button","快递盒");
		add("neo_sim.configuration.delivery.tooltip","每件送达扣款、滚动区块窗口半径");

		add("neo_sim.configuration.rebuild","重建模盒");
		add("neo_sim.configuration.rebuild.button","重建模盒");
		add("neo_sim.configuration.rebuild.tooltip","每 tick 处理上限、强制加载区块上限、每块扣款；重建完成后自动终止任务");

		add("config.neosim.announceSpawn","入城公告");
		add("config.neosim.announceDeathTemplate","死亡公告模板");
		add("config.neosim.announceEvictResident","驱逐住户公告");
		add("config.neosim.announceEvictAll","清空住户公告");
		add("config.neosim.announceMoveIn","入住公告");
		add("config.neosim.announcePregnancy","怀孕公告");
		add("config.neosim.announceBirth","出生公告");
		add("config.neosim.announceMarriage","结婚公告");
		add("config.neosim.announceCohabit","同居公告");
		add("config.neosim.announceBreakup","分手公告");
		add("config.neosim.announceRent","收租公告");
		add("config.neosim.announceDeliveryDispatch","快递派单公告");
		add("config.neosim.announceAdultLeave","成年离家公告");
		add("config.neosim.announceMissingMaterial","缺料提醒公告");
		add("config.neosim.announceBuildingComplete","完工公告");
		add("config.neosim.announceDeathCauseOldAge","死因·寿终");
		add("config.neosim.announceDeathCauseDrown","死因·淹死");
		add("config.neosim.announceDeathCauseLava","死因·岩浆");
		add("config.neosim.announceDeathCauseSuffocate","死因·窒息");
		add("config.neosim.announceDeathCauseFall","死因·摔落");
		add("config.neosim.announceDeathCauseStarve","死因·饿死");
		add("config.neosim.announceDeathCauseFire","死因·火烧");
		add("config.neosim.announceDeathCauseLightning","死因·雷击");
		add("config.neosim.announceDeathCauseCactus","死因·仙人掌");
		add("config.neosim.announceDeathCauseOther","死因·其他");
		add("config.neosim.announceDeathRemarkOld","死亡备注·寿终");
		add("config.neosim.announceDeathRemarkYoung","死亡备注·年轻");
		add("neo_sim.configuration.announce","公告文案");
		add("neo_sim.configuration.announce.button","公告文案");
		add("neo_sim.configuration.announce.tooltip","公告文案模板（%s 为占位符）与死因、死亡备注文案");
		add("neo_sim.configuration.deathCause","死亡原因");
		add("neo_sim.configuration.deathCause.button","死亡原因");
		add("neo_sim.configuration.deathCause.tooltip","各死因对应的公告文案");
		add("neo_sim.configuration.deathRemark","死亡备注");
		add("neo_sim.configuration.deathRemark.button","死亡备注");
		add("neo_sim.configuration.deathRemark.tooltip","死亡公告中寿终/年轻的备注文案");

		add("itemGroup.neosim_tab","新模拟城市");

		add("gui.neosim.run.title","运行");
		add("gui.neosim.run.buttonNormal","普通模式");
		add("gui.neosim.run.buttonCreative","创造模式");
		add("gui.neosim.run.buttonHardcore","硬核模式");
		add("gui.neosim.run.buttonClose","确定");
		add("gui.neosim.run.tipNormal","还没想好要写什么");
		add("gui.neosim.run.tipCreative","无限资金和资源");
		add("gui.neosim.run.tipHardcore","建筑需要所有方块");

		add("gui.neosim.hud.population","人口");
		add("gui.neosim.hud.day","第%s天");
		add("gui.neosim.hud.credit","资金");
		add("gui.neosim.hud.monday","星期一");
		add("gui.neosim.hud.tuesday","星期二");
		add("gui.neosim.hud.wednesday","星期三");
		add("gui.neosim.hud.thursday","星期四");
		add("gui.neosim.hud.friday","星期五");
		add("gui.neosim.hud.saturday","星期六");
		add("gui.neosim.hud.sunday","星期日");

		add("gui.neosim.city.title","城市");
		add("gui.neosim.city.add","新增城市");
		add("gui.neosim.city.choose","选择城市");
		add("gui.neosim.city.refresh","刷新列表");
		add("gui.neosim.city.buttonConfirm","确定");

		add("gui.neosim.BuildingConstructor.title","建筑模盒");
		add("gui.neosim.BuildingConstructor.statusReady","状态: 就绪");
		add("gui.neosim.BuildingConstructor.page0.hint","请为建筑模盒选择一个任务");
		add("gui.neosim.BuildingConstructor.page1.hint","请选择一种建筑类型");
		add("gui.neosim.BuildingConstructor.page2.hint","选择一个住宅建筑");
		add("gui.neosim.BuildingConstructor.page3.hint","选择一个商业建筑");
		add("gui.neosim.BuildingConstructor.page4.hint","选择一个工业建筑");
		add("gui.neosim.BuildingConstructor.page5.hint","选择其他类型建筑");
		add("gui.neosim.BuildingConstructor.page6.hint","建筑需求: %s");
		add("gui.neosim.BuildingConstructor.hireBuilder","雇佣");
		add("gui.neosim.BuildingConstructor.fireWorker","解雇 %s");
		add("gui.neosim.BuildingConstructor.chooseBuilding","选择建筑");
		add("gui.neosim.BuildingConstructor.currentStatus","当前状态");
		add("gui.neosim.BuildingConstructor.continue","继续");
		add("gui.neosim.BuildingConstructor.pause","暂停");
		add("gui.neosim.BuildingConstructor.choosePlan","选择规划");
		add("gui.neosim.BuildingConstructor.currentMissing","当前缺少");
		add("gui.neosim.BuildingConstructor.page11.hint","选择整地方案");
		add("gui.neosim.BuildingConstructor.plan.FLATTEN","推平");
		add("gui.neosim.BuildingConstructor.plan.FLATTEN.desc","挖除地块内基线以上的地形方块，掉落物入箱");
		add("gui.neosim.BuildingConstructor.plan.VALUE_PACK","铺泥土");
		add("gui.neosim.BuildingConstructor.plan.VALUE_PACK.desc","在地表基准层铺一层泥土");
		add("gui.neosim.BuildingConstructor.plan.GRASS_PACK","铺草皮");
		add("gui.neosim.BuildingConstructor.plan.GRASS_PACK.desc","在地表基准层铺一层草方块");
		add("gui.neosim.BuildingConstructor.plan.SEALAND","填水");
		add("gui.neosim.BuildingConstructor.plan.SEALAND.desc","把地块内的水体从底到顶填成泥土");
		add("gui.neosim.BuildingConstructor.plan.LAWNMOWER","割草");
		add("gui.neosim.BuildingConstructor.plan.LAWNMOWER.desc","清除地块内的草与花，掉落物入箱");
		add("gui.neosim.BuildingConstructor.plan.NATURE","植树");
		add("gui.neosim.BuildingConstructor.plan.NATURE.desc","在地表种树苗与花（每 15 块 1 树苗）");
		add("gui.neosim.BuildingConstructor.plan.DEICER","除雪");
		add("gui.neosim.BuildingConstructor.plan.DEICER.desc","清除地块内的雪层");
		add("gui.neosim.BuildingConstructor.noArchitect","请先雇佣建筑师");
		add("gui.neosim.BuildingConstructor.confirmTerraform","确认整地");
		add("gui.neosim.BuildingConstructor.terraformRate","每块 $ %s");
		add("gui.neosim.BuildingConstructor.typeResidential","住宅");
		add("gui.neosim.BuildingConstructor.typeCommercial","商业");
		add("gui.neosim.BuildingConstructor.typeIndustrial","工业");
		add("gui.neosim.BuildingConstructor.typeOther","其他");
		add("gui.neosim.BuildingConstructor.typeCustom","自定义");
		add("gui.neosim.BuildingConstructor.page9.hint","选择一个自定义建筑");
		add("gui.neosim.BuildingConstructor.page10.hint","当前缺少的建造材料: %s");
		add("gui.neosim.BuildingConstructor.add","添加自定义建筑");
		add("gui.neosim.BuildingConstructor.search","搜索");
		add("gui.neosim.BuildingConstructor.prevPage","上一页");
		add("gui.neosim.BuildingConstructor.nextPage","下一页");
		add("gui.neosim.BuildingConstructor.goBack","返回");
		add("gui.neosim.BuildingConstructor.preview","预览");
		add("gui.neosim.BuildingConstructor.previewAdjust","调整预览");
		add("gui.neosim.BuildingConstructor.refresh","刷新");
		add("gui.neosim.BuildingConstructor.buildIt","立即建造!");
		add("gui.neosim.BuildingConstructor.rotateBlockOrientation","旋转方块朝向");
		add("gui.neosim.BuildingConstructor.oldBlueprintWarning","您正在使用旧版蓝图，需要注意方块朝向是否错误");
		add("gui.neosim.BuildingConstructor.dimensions","尺寸: %s");
		add("gui.neosim.BuildingConstructor.cost","$ %s");
		add("gui.neosim.BuildingConstructor.totalBlocks","方块总数: %s");
		add("gui.neosim.BuildingConstructor.blocks","%s 个方块");
		add("gui.neosim.BuildingConstructor.noMaterials","无需材料 (空建筑)");
		add("gui.neosim.BuildingConstructor.noMaterialsCreative","创造模式：全部方块免费，无需材料");
		add("gui.neosim.BuildingConstructor.materials","材料: %s 种方块");
		add("gui.neosim.BuildingConstructor.moreTypes","  ...还有 %s 种");
		add("gui.neosim.BuildingConstructor.missingCount","缺少 %s 种材料");
		add("gui.neosim.BuildingConstructor.missingLine","缺 %s");
		add("gui.neosim.BuildingConstructor.missingNone","材料齐全，无需补充");
		add("gui.neosim.BuildingConstructor.unknownAuthor","未知");
		add("gui.neosim.BuildingConstructor.page8.hint","当前建造状态");
		add("gui.neosim.BuildingConstructor.statusBuilding","目标建筑:");
		add("gui.neosim.BuildingConstructor.statusBuilder","所选建筑师:");
		add("gui.neosim.BuildingConstructor.statusState","建造状态:");
		add("gui.neosim.BuildingConstructor.statusProgress","进度: %s / %s");
		add("gui.neosim.BuildingConstructor.statusMaterials","当前所需方块:");
		add("gui.neosim.BuildingConstructor.statusNone","无");
		add("gui.neosim.BuildingConstructor.statusState.idle","空闲");
		add("gui.neosim.BuildingConstructor.statusState.waitingWorker","等待工人");
		add("gui.neosim.BuildingConstructor.statusState.workerAssigned","已分配工人");
		add("gui.neosim.BuildingConstructor.statusState.loading","加载蓝图");
		add("gui.neosim.BuildingConstructor.statusState.waiting","等待资源");
		add("gui.neosim.BuildingConstructor.statusState.building","建造中");
		add("gui.neosim.BuildingConstructor.statusState.complete","已完成");
		add("gui.neosim.BuildingConstructor.builderLevel","建造者 Lv.%s");
		add("gui.neosim.BuildingConstructor.soulOut","灵魂出窍");
		add("gui.neosim.BuildingConstructor.adjustUp","上升");
		add("gui.neosim.BuildingConstructor.adjustDown","下降");
		add("gui.neosim.BuildingConstructor.adjustMirror","镜像");
		add("gui.neosim.BuildingConstructor.adjustRotate","旋转");
		add("gui.neosim.BuildingConstructor.dirNorth","N");
		add("gui.neosim.BuildingConstructor.dirSouth","S");
		add("gui.neosim.BuildingConstructor.dirWest","W");
		add("gui.neosim.BuildingConstructor.dirEast","E");
		add("gui.neosim.BuildingConstructor.searchModeBuilding","建筑");
		add("gui.neosim.BuildingConstructor.searchModeAuthor","作者");
		add("gui.neosim.BuildingConstructor.filterAll","全部格式");
		add("gui.neosim.BuildingConstructor.filterTxt","旧格式");
		add("gui.neosim.BuildingConstructor.filterLitematic","新格式");
		add("gui.neosim.BuildingConstructor.resetView","重置视角");
		add("gui.neosim.BuildingConstructor.scanning","正在扫描箱子…");
		add("gui.neosim.BuildingConstructor.sortNameAsc","名称 ↑");
		add("gui.neosim.BuildingConstructor.sortNameDesc","名称 ↓");
		add("gui.neosim.BuildingConstructor.sortCostAsc","造价 ↑");
		add("gui.neosim.BuildingConstructor.sortCostDesc","造价 ↓");
		add("gui.neosim.BuildingConstructor.sortAuthorAsc","作者 ↑");
		add("gui.neosim.BuildingConstructor.sortAuthorDesc","作者 ↓");

		add("gui.neosim.ControlBox.title","控制箱");
		add("gui.neosim.ControlBox.building","建筑: %s");
		add("gui.neosim.ControlBox.author","作者: %s");
		add("gui.neosim.ControlBox.placer","所建玩家: %s");
		add("gui.neosim.ControlBox.residents","居民: %s");
		add("gui.neosim.ControlBox.none","无");
		add("gui.neosim.ControlBox.noRecord","无此建筑记录");
		add("gui.neosim.ControlBox.close","关闭");
		add("gui.neosim.ControlBox.evict","驱逐");
		add("gui.neosim.ControlBox.evictAll","清空全部住户");
		add("gui.neosim.ControlBox.moveIn","入住");
		add("gui.neosim.ControlBox.homelessTitle","安排入住（无家 NPC）");
		add("gui.neosim.ControlBox.noHomeless","城市里没有无家可归的 NPC");
		add("gui.neosim.ControlBox.residentsLabel","居民");
		add("gui.neosim.ControlBox.livingPoints","生活点 %s · 已住 %s");
		add("gui.neosim.ControlBox.livingPointFree","空闲");
		add("gui.neosim.ControlBox.livingPointOccupant","住户: %s");
		add("gui.neosim.ControlBox.back","返回");

		add("gui.neosim.FarmingBox.title","农业盒");
		add("gui.neosim.FarmingBox.noRecord","无此工作盒记录");
		add("gui.neosim.FarmingBox.rect","田地：%s×%s");
		add("gui.neosim.FarmingBox.unbound","未绑定地块（请将盒子紧挨标记棒放置）");
		add("gui.neosim.FarmingBox.worker","农夫：%s");
		add("gui.neosim.FarmingBox.workerNone","暂无农夫");
		add("gui.neosim.FarmingBox.workerLevel","农夫等级：%s");
		add("gui.neosim.FarmingBox.hire","雇佣");
		add("gui.neosim.FarmingBox.fire","解雇 %s");
		add("gui.neosim.FarmingBox.target","目标");
		add("gui.neosim.FarmingBox.targetTitle","目标");
		add("gui.neosim.FarmingBox.targetSummary","目标：%s");
		add("gui.neosim.FarmingBox.targetNone","未设置");
		add("gui.neosim.FarmingBox.typeWHEAT","小麦");
		add("gui.neosim.FarmingBox.typeCARROT","胡萝卜");
		add("gui.neosim.FarmingBox.typePOTATO","土豆");
		add("gui.neosim.FarmingBox.useBoneMeal","使用骨粉");
		add("gui.neosim.FarmingBox.livestock","牲畜");
		add("gui.neosim.FarmingBox.industryPlant","种植业");
		add("gui.neosim.FarmingBox.industryLivestock","畜牧业");
		add("gui.neosim.FarmingBox.animalCHICKEN","鸡");
		add("gui.neosim.FarmingBox.animalPIG","猪");
		add("gui.neosim.FarmingBox.animalCOW","牛");
		add("gui.neosim.FarmingBox.animalSHEEP","羊");
		add("gui.neosim.FarmingBox.apply","确认");
		add("gui.neosim.FarmingBox.pause","暂停");
		add("gui.neosim.FarmingBox.resume","继续");
		add("gui.neosim.FarmingBox.close","关闭");
		add("gui.neosim.FarmingBox.hireTitle","选择农夫");
		add("gui.neosim.FarmingBox.goBack","返回");
		add("gui.neosim.FarmingBox.state","状态：%s");
		add("gui.neosim.FarmingBox.state.idle","空闲");
		add("gui.neosim.FarmingBox.state.waitingWorker","等待农夫");
		add("gui.neosim.FarmingBox.state.workerAssigned","农夫已就位");
		add("gui.neosim.FarmingBox.state.checkingChests","检查箱子");
		add("gui.neosim.FarmingBox.state.harvest","收割中");
		add("gui.neosim.FarmingBox.state.till","翻地中");
		add("gui.neosim.FarmingBox.state.plant","种植中");
		add("gui.neosim.FarmingBox.state.waitingSeed","缺少种子");
		add("gui.neosim.FarmingBox.state.raise","畜牧中");
		add("gui.neosim.FarmingBox.state.waitingFeed","缺少饲料");
		add("gui.neosim.FarmingBox.state.waitingChest","箱子已满");
		add("gui.neosim.FarmingBox.state.depleted","已采尽");
		add("gui.neosim.FarmingBox.forestry","林业：%s");
		add("gui.neosim.FarmingBox.industryForestry","林业");
		add("gui.neosim.FarmingBox.treeOAK","橡树");
		add("gui.neosim.FarmingBox.treeBIRCH","白桦");
		add("gui.neosim.FarmingBox.treeSPRUCE","云杉");
		add("gui.neosim.FarmingBox.treeJUNGLE","丛林");
		add("gui.neosim.FarmingBox.treeACACIA","金合欢");
		add("gui.neosim.FarmingBox.treeCHERRY","樱花");
		add("gui.neosim.FarmingBox.state.chop","伐木中");
		add("gui.neosim.FarmingBox.state.waitingSapling","缺少树苗");

		add("gui.neosim.MiningBox.title","矿业盒");
		add("gui.neosim.MiningBox.noRecord","无此工作盒记录");
		add("gui.neosim.MiningBox.rect","矿区：%s×%s");
		add("gui.neosim.MiningBox.unbound","未绑定地块（请将盒子紧挨标记棒放置）");
		add("gui.neosim.MiningBox.depth","深度：挖至 y=%s");
		add("gui.neosim.MiningBox.worker","矿工：%s");
		add("gui.neosim.MiningBox.workerNone","暂无矿工");

		add("gui.neosim.hire.search","搜索名字");
		add("gui.neosim.hire.searchHint","输入名字…");
		add("gui.neosim.hire.minLevel","最小等级");
		add("gui.neosim.hire.minLevelHint","输入最小等级…");
		add("gui.neosim.hire.hireableOnly","仅可雇佣");
		add("gui.neosim.hire.prev","上一页");
		add("gui.neosim.hire.next","下一页");
		add("gui.neosim.hire.page","%s/%s");
		add("gui.neosim.hire.level","Lv.%s");
		add("gui.neosim.hire.reason.underage","未成年");
		add("gui.neosim.hire.reason.maternity","产假中");
		add("gui.neosim.hire.reason.hired","已在别处工作");
		add("gui.neosim.hire.none","没有符合条件的市民");
		add("gui.neosim.hire.back","返回");
		add("gui.neosim.BuildingConstructor.hireTitle","选择建筑师");
		add("gui.neosim.MiningBox.workerLevel","矿工等级：%s");
		add("gui.neosim.MiningBox.hire","雇佣");
		add("gui.neosim.MiningBox.fire","解雇 %s");
		add("gui.neosim.MiningBox.discards","丢弃");
		add("gui.neosim.MiningBox.catDirt","泥土/草方块");
		add("gui.neosim.MiningBox.catStone","石头/圆石");
		add("gui.neosim.MiningBox.catSand","沙子/红沙");
		add("gui.neosim.MiningBox.apply","确认");
		add("gui.neosim.MiningBox.discardTitle","丢弃过滤");
		add("gui.neosim.MiningBox.pause","暂停");
		add("gui.neosim.MiningBox.resume","继续");
		add("gui.neosim.MiningBox.close","关闭");
		add("gui.neosim.MiningBox.hireTitle","选择矿工");
		add("gui.neosim.MiningBox.goBack","返回");
		add("gui.neosim.MiningBox.state","状态：%s");
		add("gui.neosim.MiningBox.state.idle","空闲");
		add("gui.neosim.MiningBox.state.waitingWorker","等待矿工");
		add("gui.neosim.MiningBox.state.workerAssigned","矿工已就位");
		add("gui.neosim.MiningBox.state.checkingChests","检查箱子");
		add("gui.neosim.MiningBox.state.mining","采挖中");
		add("gui.neosim.MiningBox.state.waitingChest","箱子已满");
		add("gui.neosim.MiningBox.state.depleted","已采尽");

		add("entity.neo_sim.nsnpc","新模拟城市NPC");

		add("gui.neosim.npc.title","NPC");
		add("gui.neosim.npc.setSkin","设置皮肤");
		add("gui.neosim.npc.rename","重命名");
		add("gui.neosim.npc.rename.surname","姓");
		add("gui.neosim.npc.rename.givenName","名");
		add("gui.neosim.npc.rename.confirm","确认");
		add("gui.neosim.npc.rename.cancel","取消");
		add("gui.neosim.npc.back","返回");
		add("gui.neosim.npc.info.sex","性别: %s");
		add("gui.neosim.npc.info.male","男");
		add("gui.neosim.npc.info.female","女");
		add("gui.neosim.npc.info.city","城市: %s");
		add("gui.neosim.npc.info.noCity","无");
		add("gui.neosim.npc.info.age","年龄: %d");
		add("gui.neosim.npc.info.home","家: %s");
		add("gui.neosim.npc.info.noHome","无");
		add("gui.neosim.npc.info.relationship","关系: %s");
		add("gui.neosim.npc.info.single","单身");
		add("gui.neosim.npc.info.livingWithSomeone","与他人同居");
		add("gui.neosim.npc.info.maternityLeave","产假中");
		add("gui.neosim.npc.skin.prevPage","上一页");
		add("gui.neosim.npc.skin.nextPage","下一页");
		add("gui.neosim.npc.skin.openFolder","添加自定义皮肤");
		add("gui.neosim.npc.skin.searchPlayer","输入玩家名");
		add("gui.neosim.npc.skin.searchConfirm","确定");
		add("gui.neosim.npc.skin.searching","正在搜索...");
		add("gui.neosim.npc.skin.searchFailed","失败");
		add("gui.neosim.npc.family.open","族谱");
		add("gui.neosim.npc.family.father","父亲");
		add("gui.neosim.npc.family.mother","母亲");
		add("gui.neosim.npc.family.son","儿子");
		add("gui.neosim.npc.family.daughter","女儿");
		add("gui.neosim.npc.family.brother","兄弟");
		add("gui.neosim.npc.family.sister","姐妹");
		add("gui.neosim.npc.family.grandfather","祖父");
		add("gui.neosim.npc.family.grandmother","祖母");
		add("gui.neosim.npc.family.partner","配偶");
		add("gui.neosim.npc.family.fatherInLaw","配偶父亲");
		add("gui.neosim.npc.family.motherInLaw","配偶母亲");
		add("gui.neosim.npc.family.loading","加载中…");
		add("gui.neosim.npc.family.empty","暂无亲属数据");
		add("gui.neosim.npc.family.reset","复位");
		add("gui.neosim.npc.family.tooMany","亲属过多，仅显示前 50 位");

		add("config.neosim.initialCredit","初始信用点");
		add("config.neosim.initialCredit.tooltip","城市的初始信用点");
		add("config.neosim.creditsPerBlock","每方块信用点");
		add("config.neosim.creditsPerBlock.tooltip","每放置一个方块扣除的信用点");
		add("config.neosim.maxPopulation","最大人口数");
		add("config.neosim.maxPopulation.tooltip","城市的最大人口数");
		add("config.neosim.npcMinAge","NPC最小年龄");
		add("config.neosim.npcMinAge.tooltip","NPC的最小随机年龄");
		add("config.neosim.npcMaxAge","NPC最大年龄");
		add("config.neosim.npcMaxAge.tooltip","NPC的最大随机年龄");
		add("config.neosim.npcNameLocale","NPC 姓名池语言");
		add("config.neosim.npcNameLocale.tooltip","auto=跟随创建该 NPC 的玩家语言；zh=永远中文名；en=永远英文名（已存在的 NPC 不受影响）");
		add("config.neosim.lifeRentDefault","住宅默认租金");
		add("config.neosim.lifeRentDefault.tooltip","每天每座有居民的住宅收取的租金，未按体积定价的记录使用此默认值");
		add("config.neosim.lifeRentPerBlock","按建筑体积定价系数");
		add("config.neosim.lifeRentPerBlock.tooltip","完工住宅按非空气方块数×该系数计算每日租金");
		add("config.neosim.lifeAdultAge","成年年龄");
		add("config.neosim.lifeAdultAge.tooltip","居民长到该年龄即成年：可被雇佣，跨过该年龄当天退父母家并开始找房子");
		add("config.neosim.lifeMaxAge","寿终年龄");
		add("config.neosim.lifeMaxAge.tooltip","超过该年龄后，居民每天有1/10概率自然寿终");
		add("config.neosim.lifeAgingAdultDay","成人每周长岁日");
		add("config.neosim.lifeAgingAdultDay.tooltip","成人每周长岁的星期");
		add("config.neosim.lifeAgingChildDays","儿童每周长岁日");
		add("config.neosim.lifeAgingChildDays.tooltip","儿童每周长岁的星期列表");
		add("config.neosim.lifeMarriageChance","结婚概率");
		add("config.neosim.lifeMarriageChance.tooltip","BESTFRIENDS满级时掷硬币结婚的概率");
		add("config.neosim.lifePregnancyDays","孕期天数");
		add("config.neosim.lifePregnancyDays.tooltip","从怀孕到分娩的天数");
		add("config.neosim.lifePregnancyChance","怀孕概率");
		add("config.neosim.lifePregnancyChance.tooltip","怀孕概率（1/7）");
		add("config.neosim.lifeRestChance","居家休息概率");
		add("config.neosim.lifeRestChance.tooltip","有家无业市民白天在家休息、不外出社交的概率");
		add("config.neosim.restStartHour","休息开始（游戏内小时）");
		add("config.neosim.restStartHour.tooltip","市民/工人开始休息的时刻，0-23 时，支持跨午夜（默认 18 点）");
		add("config.neosim.restEndHour","休息结束（游戏内小时）");
		add("config.neosim.restEndHour.tooltip","市民/工人结束休息的时刻，0-23 时（默认次日 6 点）");
		add("config.neosim.lifePregnancyMaxAge","受孕上限年龄");
		add("config.neosim.lifePregnancyMaxAge.tooltip","女性超过该年龄后不再参与受孕");
		add("config.neosim.lifePregnancyStartStage","受孕初始孕期进度");
		add("config.neosim.lifePregnancyStartStage.tooltip","受孕瞬间孕期进度的初始值，越高则总孕期越短");
		add("config.neosim.lifeSocialRange","社交寻找半径");
		add("config.neosim.lifeSocialRange.tooltip","无业市民白天寻找社交对象的最大距离（格）");
		add("config.neosim.lifeSocialArriveDist","社交判定范围");
		add("config.neosim.lifeSocialArriveDist.tooltip","两人相距达到该值（格）即视为到达、开始凑在一起聊天");
		add("config.neosim.lifeRelationshipDowngradeChance","关系变差概率");
		add("config.neosim.lifeRelationshipDowngradeChance.tooltip","每次社交结算时关系下降而非上升的概率");
		add("config.neosim.lifeRelationshipChangeMax","单次关系增减量上限");
		add("config.neosim.lifeRelationshipChangeMax.tooltip","每次社交结算时关系增减幅度的最大值");
		add("config.neosim.lifeMarriageSubLevel","结婚所需关系度");
		add("config.neosim.lifeMarriageSubLevel.tooltip","BESTFRIENDS 关系达到该子等级后才会触发结婚判定");
		add("config.neosim.workFarmCreditPerBlock","农业每方块信用点");
		add("config.neosim.workFarmCreditPerBlock.tooltip","农夫每收成一格作物返还的信用点");
		add("config.neosim.workFarmMaxAdults","畜牧成年上限");
		add("config.neosim.workFarmMaxAdults.tooltip","围栏内成年牲畜数超过该值即自动屠宰一只");
		add("config.neosim.workFarmMaxTotal","畜牧总量上限");
		add("config.neosim.workFarmMaxTotal.tooltip","围栏内牲畜总数达到该值即停止繁殖");
		add("config.neosim.workFarmBabyGrowMinutes","畜牧幼崽长大分钟数");
		add("config.neosim.workFarmBabyGrowMinutes.tooltip","幼崽出生后经过该分钟数即长大成年（默认5分钟）");
		add("config.neosim.workFarmBreedCooldownSeconds","畜牧繁殖冷却（秒）");
		add("config.neosim.workFarmBreedCooldownSeconds.tooltip","某物种成功繁殖后的冷却秒数（0=关闭）");
		add("config.neosim.workMineCreditPerBlock","矿业每方块信用点");
		add("config.neosim.workMineCreditPerBlock.tooltip","矿工每挖掉一格方块返还的信用点");
		add("config.neosim.workMineDiscards","矿业默认丢弃");
		add("config.neosim.workMineDiscards.tooltip","矿工默认丢弃的方块类别");

		add("neo_sim.configuration.title","%s 配置");
		add("neo_sim.configuration.section.neo.sim.toml.title","%s 通用配置");
		add("neo_sim.configuration.section.neo.sim.toml","%s 配置");
		add("neo_sim.configuration.general","通用");
		add("neo_sim.configuration.general.button","通用");
		add("neo_sim.configuration.general.tooltip","城市初始资金、建造费用、人口上限与 NPC 年龄范围");
		add("neo_sim.configuration.life","生活系统");
		add("neo_sim.configuration.life.button","生活系统");
		add("neo_sim.configuration.life.tooltip","居民生命周期相关参数");
		add("neo_sim.configuration.rent","房租与收入");
		add("neo_sim.configuration.rent.button","房租与收入");
		add("neo_sim.configuration.rent.tooltip","住宅每日收租的默认值与按建筑体积定价系数");
		add("neo_sim.configuration.aging","衰老与寿终");
		add("neo_sim.configuration.aging.button","衰老与寿终");
		add("neo_sim.configuration.aging.tooltip","成年年龄、寿终年龄与每周长岁日");
		add("neo_sim.configuration.rest","作息");
		add("neo_sim.configuration.rest.button","作息");
		add("neo_sim.configuration.rest.tooltip","有家无业市民白天居家休息概率");
		add("neo_sim.configuration.reproduction","生育与分娩");
		add("neo_sim.configuration.reproduction.button","生育与分娩");
		add("neo_sim.configuration.reproduction.tooltip","孕期天数、怀孕概率、受孕上限年龄与初始孕期进度");
		add("neo_sim.configuration.social","社交与串门");
		add("neo_sim.configuration.social.button","社交与串门");
		add("neo_sim.configuration.social.tooltip","无业市民白天社交的寻找半径与到达判定距离");
		add("neo_sim.configuration.relationship","关系增减");
		add("neo_sim.configuration.relationship.button","关系增减");
		add("neo_sim.configuration.relationship.tooltip","每次社交结算时关系变差概率与增减量上限");
		add("neo_sim.configuration.marriage","婚姻");
		add("neo_sim.configuration.marriage.button","婚姻");
		add("neo_sim.configuration.marriage.tooltip","结婚概率与结婚所需关系度");
		add("neo_sim.configuration.workplot","农业与矿业");
		add("neo_sim.configuration.workplot.button","农业与矿业");
		add("neo_sim.configuration.workplot.tooltip","工作盒绑定半径、农业/矿业每方块信用点");

		// 玩家提示与公告（按客户端语言解析）
		add("msg.neosim.city.nameEmpty","§c城市名不能为空");
		add("msg.neosim.city.illegalChars","§c城市名含有非法字符");
		add("msg.neosim.city.exists","§c城市已存在");
		add("msg.neosim.city.alreadyJoined","§c你已经加入了城市");
		add("msg.neosim.city.notFound","§c城市不存在");
		add("msg.neosim.city.joinedOther","§c你已经加入了其他城市");
		add("msg.neosim.worker.noCity","§c请先加入城市");
		add("msg.neosim.worker.invalidCitizen","§c无效的市民");
		add("msg.neosim.worker.alreadyWorking","§c该市民已在别处工作");
		add("msg.neosim.worker.noProfile","§c市民档案不存在");
		add("msg.neosim.worker.underage","§c未成年不可雇佣");
		add("msg.neosim.worker.maternity","§c产假中不可雇佣");
		add("msg.neosim.worker.restoreFailed","§c市民恢复失败");
		add("msg.neosim.worker.notYourCity","§c该市民不属于你的城市");
		add("msg.neosim.worker.noHirePost","§c此处没有可雇佣的岗位");
		add("msg.neosim.worker.noFirePost","§c此处没有可解雇的岗位");
		add("msg.neosim.living.noNpc","§c没有指定 NPC");
		add("msg.neosim.living.npcNotFound","§c找不到 NPC: §f%s");
		add("msg.neosim.living.notYourCity","§c%s §e不属于这座城市");
		add("msg.neosim.living.alreadyHasHome","§c%s §e已经有家了");
		add("msg.neosim.living.noFreeRoom","§c没有空房间");
		add("msg.neosim.terraform.noCity","§c请先加入城市");
		add("msg.neosim.terraform.boxMissing","§c建筑模盒不存在");
		add("msg.neosim.terraform.taskExists","§c该模盒已有整地任务");
		add("msg.neosim.terraform.buildingRunning","§c当前有进行中的建造任务，请先完成或取消");
		add("msg.neosim.terraform.invalidRect","§c地块无效");
		add("msg.neosim.terraform.tooLarge","§c地块过大（单边不能超过 %s 格）");
		add("msg.neosim.terraform.baselineOutOfRange","§c地表基准超出世界高度");
		add("msg.neosim.terraform.markerNotAdjacent","§c标记棒需与建筑模盒相连才能构成地块");
		add("msg.neosim.terraform.markerMismatch","§c地块与标记不符，请重新圈地");
		add("msg.neosim.terraform.noTargets","§c该地块内没有可整地的目标");
		add("msg.neosim.terraform.noMarkerRect","§c请先用标记棒圈出矩形地块，且标记需与模盒相连");
		add("msg.neosim.terraform.running","§c整地进行中，请先完成整地");
		add("msg.neosim.terraform.needChest","§e整地需要箱子：请在建筑模盒旁放置一个箱子");
		add("msg.neosim.terraform.planMissing","§e整地任务已失效（方案不存在）");
		add("msg.neosim.terraform.scanEmpty","§e该地块内没有可整地的目标");
		add("msg.neosim.terraform.complete","§e整地完成！");
		add("msg.neosim.terraform.missingMaterial","§c整地缺料：%s，请放入模盒旁的箱子");

		// 重建模盒
		add("msg.neosim.workbox.disabled","§e该工作盒已在配置中关闭");
		add("msg.neosim.rebuild.noControlBox","§e请把重建模盒放在已登记的建筑控制箱旁");
		add("msg.neosim.rebuild.noSchematic","§c蓝图不存在：%s");
		add("msg.neosim.rebuild.bound","§a重建模盒已绑定：%s");
		add("msg.neosim.rebuild.unbound","§e重建模盒：未绑定（请放在控制箱旁）");
		add("msg.neosim.rebuild.idle","§e重建模盒：已完成或未绑定（重放可再次工作）");
		add("msg.neosim.rebuild.status","§e重建模盒：%s（%s）");
		add("msg.neosim.rebuild.state.running","运行中");
		add("msg.neosim.rebuild.state.waiting","缺料，等待箱子补充");
		add("msg.neosim.rebuild.state.complete","已完成");
		add("msg.neosim.rebuild.state.unbound","未绑定");
		add("msg.neosim.preview.overlap","§c无法放置：区域与已有建筑重叠");
		add("msg.neosim.payload.rateLimited","§c请稍后再试");
		add("msg.neosim.payload.invalidPlan","§c无效的整地方案");
		add("msg.neosim.delivery.noChest","工地无箱子");
		add("msg.neosim.delivery.stationMissing","站点缺少 %s");
		add("msg.neosim.command.cityNotFound","§c城市 '%s' 不存在");
		add("msg.neosim.command.summonBlocked","§c请用 Neo-Sim 指令生成 NPC，禁止 /summon");
		add("announce.neosim.spawn","§f%s §e来到了城市");
		add("announce.neosim.deathTemplate","§f%s §e%s §f(%s)");
		add("announce.neosim.evictResident","§f%s §e被赶出了 §f%s");
		add("announce.neosim.evictAll","§f%s §e已清空，§f%s §e名住户被赶出");
		add("announce.neosim.moveIn","§f%s §e搬进了 §f%s");
		add("announce.neosim.pregnancy","§f好消息！§f%s §e和 §f%s §e要有宝宝了！");
		add("announce.neosim.birth","§f%s §e诞生了！");
		add("announce.neosim.marriage","§f%s §e与 §f%s §e结为夫妻了");
		add("announce.neosim.cohabit","§f%s §e与 §f%s §e开始同居了");
		add("announce.neosim.breakup","§f%s §e和 §f%s §e的关系破裂了，结束了同居生活");
		add("announce.neosim.rent","§e今天共收取了 §f $%s");
		add("announce.neosim.deliveryDispatch","§e%s §f正前往 §e%s §f运送 §e%s §f个 §e%s");
		add("announce.neosim.adultLeave","§f%s §e现在 %s 岁了，他们会开始找房子，你也可以雇佣他们了");
		add("announce.neosim.missingMaterial","§6建造 §f%s §e缺少材料 §b%s");
		add("announce.neosim.buildingComplete","§f%s §e已完工");
		add("announce.neosim.deathCause.oldAge","年纪大了，感觉不太舒服……哦不！");
		add("announce.neosim.deathCause.drown","淹死了");
		add("announce.neosim.deathCause.lava","掉进了岩浆里");
		add("announce.neosim.deathCause.suffocate","被卡在墙里窒息了");
		add("announce.neosim.deathCause.fall","从高处摔了下来");
		add("announce.neosim.deathCause.starve","饿死了（建个农场吧…）");
		add("announce.neosim.deathCause.fire","被火烧死了");
		add("announce.neosim.deathCause.lightning","被雷劈了");
		add("announce.neosim.deathCause.cactus","被仙人掌扎了");
		add("announce.neosim.deathCause.other","不幸去世了");
		add("announce.neosim.deathRemark.old","享年 %s 岁，也算寿终正寝了！");
		add("announce.neosim.deathRemark.young","年仅 %s 岁");

		// 蓝图名：供服务端公告/提示按客户端语言显示建筑名（英文等语言在代码里用 fallback 回落原名）
		addBlueprintNames();
	}

	private void addBlueprintNames()
	{
		try (InputStream is = LangZhCn.class.getResourceAsStream("/assets/neo_sim/buildings/zh_cn_names.json"))
		{
			if (is == null) return;
			try (Reader reader = new InputStreamReader(is, StandardCharsets.UTF_8))
			{
				JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
				for (Map.Entry<String, JsonElement> e : root.entrySet())
				{
					add("blueprint.neosim." + e.getKey(), e.getValue().getAsString());
				}
			}
		}
		catch (Exception ignored)
		{
			// 汉化表缺失不影响其余语言键生成
		}
	}
}
