package com.wenzai.neosim.datagen;

import com.wenzai.neosim.NeoSim;
import com.wenzai.neosim.block.ModBlocks;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class LangZhCn extends LanguageProvider
{
	public LangZhCn(PackOutput output)
	{
		super(output, NeoSim.MOD_ID, "zh_cn");
	}

	@Override
	protected void addTranslations()
	{
		add(ModBlocks.BUILDING_CONSTRUCTOR.get(), "建筑模盒");
		add(ModBlocks.CONTROL_BOX.get(), "控制箱");
		add(ModBlocks.MARKER.get(), "标记棒");
		add(ModBlocks.FARMING_BOX.get(), "农业盒");
		add(ModBlocks.MINING_BOX.get(), "矿业盒");
		add(ModBlocks.DELIVERY_BOX.get(), "快递盒");
		add(ModBlocks.LIVING_POINT.get(), "生活点");

		add("gui.neosim.DeliveryBox.title","快递盒");
		add("gui.neosim.DeliveryBox.worker","快递员：%s");
		add("gui.neosim.DeliveryBox.workerNone","暂无快递员");
		add("gui.neosim.DeliveryBox.workerLevel","快递员等级：%s");
		add("gui.neosim.DeliveryBox.hire","雇佣");
		add("gui.neosim.DeliveryBox.fire","解雇");
		add("gui.neosim.DeliveryBox.pause","暂停");
		add("gui.neosim.DeliveryBox.resume","继续");
		add("gui.neosim.DeliveryBox.close","关闭");
		add("gui.neosim.DeliveryBox.hireTitle","选择快递员");
		add("gui.neosim.DeliveryBox.goBack","返回");
		add("gui.neosim.DeliveryBox.state","状态：%s");
		add("gui.neosim.DeliveryBox.state.idle","待命");
		add("gui.neosim.DeliveryBox.state.waitingWorker","等待快递员");
		add("gui.neosim.DeliveryBox.state.workerAssigned","快递员就位");
		add("gui.neosim.DeliveryBox.state.walking","配送中");
		add("gui.neosim.DeliveryBox.state.depositing","投料中");
		add("gui.neosim.DeliveryBox.state.returning","返回站点");

		add("config.neosim.deliveryCreditPerUnit","每件材料送达扣款");
		add("config.neosim.deliveryChunkRadius","快递员区块窗口半径");
		add("neo_sim.configuration.delivery","快递盒");
		add("neo_sim.configuration.delivery.button","快递盒");
		add("neo_sim.configuration.delivery.tooltip","每件送达扣款、滚动区块窗口半径");

		add("config.neosim.announceSpawn","入城公告");
		add("config.neosim.announceDeathTemplate","死亡公告模板");
		add("config.neosim.announceEvictResident","驱逐住户公告");
		add("config.neosim.announceEvictAll","清空住户公告");
		add("config.neosim.announceMoveIn","入住公告");
		add("config.neosim.announcePregnancy","怀孕公告");
		add("config.neosim.announceBirth","出生公告");
		add("config.neosim.announceMarriage","结婚公告");
		add("config.neosim.announceCohabit","同居公告");
		add("config.neosim.announceBreakup","分手公告");
		add("config.neosim.announceRent","收租公告");
		add("config.neosim.announceDeliveryDispatch","快递派单公告");
		add("config.neosim.announceAdultLeave","成年离家公告");
		add("config.neosim.announceMissingMaterial","缺料提醒公告");
		add("config.neosim.announceBuildingComplete","完工公告");
		add("config.neosim.announceDeathCauseOldAge","死因·寿终");
		add("config.neosim.announceDeathCauseDrown","死因·淹死");
		add("config.neosim.announceDeathCauseLava","死因·岩浆");
		add("config.neosim.announceDeathCauseSuffocate","死因·窒息");
		add("config.neosim.announceDeathCauseFall","死因·摔落");
		add("config.neosim.announceDeathCauseStarve","死因·饿死");
		add("config.neosim.announceDeathCauseFire","死因·火烧");
		add("config.neosim.announceDeathCauseLightning","死因·雷击");
		add("config.neosim.announceDeathCauseCactus","死因·仙人掌");
		add("config.neosim.announceDeathCauseOther","死因·其他");
		add("config.neosim.announceDeathRemarkOld","死亡备注·寿终");
		add("config.neosim.announceDeathRemarkYoung","死亡备注·年轻");
		add("neo_sim.configuration.announce","公告文案");
		add("neo_sim.configuration.announce.button","公告文案");
		add("neo_sim.configuration.announce.tooltip","公告文案模板（%s 为占位符）与死因、死亡备注文案");
		add("neo_sim.configuration.deathCause","死亡原因");
		add("neo_sim.configuration.deathCause.button","死亡原因");
		add("neo_sim.configuration.deathCause.tooltip","各死因对应的公告文案");
		add("neo_sim.configuration.deathRemark","死亡备注");
		add("neo_sim.configuration.deathRemark.button","死亡备注");
		add("neo_sim.configuration.deathRemark.tooltip","死亡公告中寿终/年轻的备注文案");

		add("itemGroup.neosim_tab","新模拟城市");

		add("gui.neosim.run.title","运行");
		add("gui.neosim.run.buttonNormal","普通模式");
		add("gui.neosim.run.buttonCreative","创造模式");
		add("gui.neosim.run.buttonHardcore","硬核模式");
		add("gui.neosim.run.buttonClose","确定");
		add("gui.neosim.run.tipNormal","还没想好要写什么");
		add("gui.neosim.run.tipCreative","无限资金和资源");
		add("gui.neosim.run.tipHardcore","建筑需要所有方块");

		add("gui.neosim.hud.population","人口");
		add("gui.neosim.hud.day","第%s天");
		add("gui.neosim.hud.credit","资金");
		add("gui.neosim.hud.monday","星期一");
		add("gui.neosim.hud.tuesday","星期二");
		add("gui.neosim.hud.wednesday","星期三");
		add("gui.neosim.hud.thursday","星期四");
		add("gui.neosim.hud.friday","星期五");
		add("gui.neosim.hud.saturday","星期六");
		add("gui.neosim.hud.sunday","星期日");

		add("gui.neosim.city.title","城市");
		add("gui.neosim.city.add","新增城市");
		add("gui.neosim.city.choose","选择城市");
		add("gui.neosim.city.refresh","刷新列表");
		add("gui.neosim.city.buttonConfirm","确定");

		add("gui.neosim.BuildingConstructor.title","建筑模盒");
		add("gui.neosim.BuildingConstructor.statusReady","状态: 就绪");
		add("gui.neosim.BuildingConstructor.page0.hint","请为建筑模盒选择一个任务");
		add("gui.neosim.BuildingConstructor.page1.hint","请选择一种建筑类型");
		add("gui.neosim.BuildingConstructor.page2.hint","选择一个住宅建筑");
		add("gui.neosim.BuildingConstructor.page3.hint","选择一个商业建筑");
		add("gui.neosim.BuildingConstructor.page4.hint","选择一个工业建筑");
		add("gui.neosim.BuildingConstructor.page5.hint","选择其他类型建筑");
		add("gui.neosim.BuildingConstructor.page6.hint","建筑需求: %s");
		add("gui.neosim.BuildingConstructor.hireBuilder","雇佣");
		add("gui.neosim.BuildingConstructor.fireWorker","解雇 %s");
		add("gui.neosim.BuildingConstructor.chooseBuilding","选择建筑");
		add("gui.neosim.BuildingConstructor.currentStatus","当前状态");
		add("gui.neosim.BuildingConstructor.continue","继续");
		add("gui.neosim.BuildingConstructor.pause","暂停");
		add("gui.neosim.BuildingConstructor.choosePlan","选择规划");
		add("gui.neosim.BuildingConstructor.currentMissing","当前缺少");
		add("gui.neosim.BuildingConstructor.page11.hint","选择整地方案");
		add("gui.neosim.BuildingConstructor.plan.FLATTEN","推平");
		add("gui.neosim.BuildingConstructor.plan.FLATTEN.desc","挖除地块内基线以上的地形方块，掉落物入箱");
		add("gui.neosim.BuildingConstructor.plan.VALUE_PACK","铺泥土");
		add("gui.neosim.BuildingConstructor.plan.VALUE_PACK.desc","在地表基准层铺一层泥土");
		add("gui.neosim.BuildingConstructor.plan.GRASS_PACK","铺草皮");
		add("gui.neosim.BuildingConstructor.plan.GRASS_PACK.desc","在地表基准层铺一层草方块");
		add("gui.neosim.BuildingConstructor.plan.SEALAND","填水");
		add("gui.neosim.BuildingConstructor.plan.SEALAND.desc","把地块内的水体从底到顶填成泥土");
		add("gui.neosim.BuildingConstructor.plan.LAWNMOWER","割草");
		add("gui.neosim.BuildingConstructor.plan.LAWNMOWER.desc","清除地块内的草与花，掉落物入箱");
		add("gui.neosim.BuildingConstructor.plan.NATURE","植树");
		add("gui.neosim.BuildingConstructor.plan.NATURE.desc","在地表种树苗与花（每 15 块 1 树苗）");
		add("gui.neosim.BuildingConstructor.plan.DEICER","除雪");
		add("gui.neosim.BuildingConstructor.plan.DEICER.desc","清除地块内的雪层");
		add("gui.neosim.BuildingConstructor.noArchitect","请先雇佣建筑师");
		add("gui.neosim.BuildingConstructor.confirmTerraform","确认整地");
		add("gui.neosim.BuildingConstructor.terraformRate","每块 $ %s");
		add("gui.neosim.BuildingConstructor.typeResidential","住宅");
		add("gui.neosim.BuildingConstructor.typeCommercial","商业");
		add("gui.neosim.BuildingConstructor.typeIndustrial","工业");
		add("gui.neosim.BuildingConstructor.typeOther","其他");
		add("gui.neosim.BuildingConstructor.typeCustom","自定义");
		add("gui.neosim.BuildingConstructor.page9.hint","选择一个自定义建筑");
		add("gui.neosim.BuildingConstructor.page10.hint","当前缺少的建造材料: %s");
		add("gui.neosim.BuildingConstructor.add","添加自定义建筑");
		add("gui.neosim.BuildingConstructor.search","搜索");
		add("gui.neosim.BuildingConstructor.prevPage","上一页");
		add("gui.neosim.BuildingConstructor.nextPage","下一页");
		add("gui.neosim.BuildingConstructor.goBack","返回");
		add("gui.neosim.BuildingConstructor.preview","预览");
		add("gui.neosim.BuildingConstructor.previewAdjust","调整预览");
		add("gui.neosim.BuildingConstructor.refresh","刷新");
		add("gui.neosim.BuildingConstructor.buildIt","立即建造!");
		add("gui.neosim.BuildingConstructor.rotateBlockOrientation","旋转方块朝向");
		add("gui.neosim.BuildingConstructor.oldBlueprintWarning","您正在使用旧版蓝图，需要注意方块朝向是否错误");
		add("gui.neosim.BuildingConstructor.dimensions","尺寸: %s");
		add("gui.neosim.BuildingConstructor.cost","$ %s");
		add("gui.neosim.BuildingConstructor.totalBlocks","方块总数: %s");
		add("gui.neosim.BuildingConstructor.blocks","%s 个方块");
		add("gui.neosim.BuildingConstructor.noMaterials","无需材料 (空建筑)");
		add("gui.neosim.BuildingConstructor.noMaterialsCreative","创造模式：全部方块免费，无需材料");
		add("gui.neosim.BuildingConstructor.materials","材料: %s 种方块");
		add("gui.neosim.BuildingConstructor.moreTypes","  ...还有 %s 种");
		add("gui.neosim.BuildingConstructor.missingCount","缺少 %s 种材料");
		add("gui.neosim.BuildingConstructor.missingLine","缺 %s");
		add("gui.neosim.BuildingConstructor.missingNone","材料齐全，无需补充");
		add("gui.neosim.BuildingConstructor.unknownAuthor","未知");
		add("gui.neosim.BuildingConstructor.page8.hint","当前建造状态");
		add("gui.neosim.BuildingConstructor.statusBuilding","目标建筑:");
		add("gui.neosim.BuildingConstructor.statusBuilder","所选建筑师:");
		add("gui.neosim.BuildingConstructor.statusState","建造状态:");
		add("gui.neosim.BuildingConstructor.statusProgress","进度: %s / %s");
		add("gui.neosim.BuildingConstructor.statusMaterials","当前所需方块:");
		add("gui.neosim.BuildingConstructor.statusNone","无");
		add("gui.neosim.BuildingConstructor.statusState.idle","空闲");
		add("gui.neosim.BuildingConstructor.statusState.waitingWorker","等待工人");
		add("gui.neosim.BuildingConstructor.statusState.workerAssigned","已分配工人");
		add("gui.neosim.BuildingConstructor.statusState.loading","加载蓝图");
		add("gui.neosim.BuildingConstructor.statusState.waiting","等待资源");
		add("gui.neosim.BuildingConstructor.statusState.building","建造中");
		add("gui.neosim.BuildingConstructor.statusState.complete","已完成");
		add("gui.neosim.BuildingConstructor.builderLevel","建造者 Lv.%s");
		add("gui.neosim.BuildingConstructor.soulOut","灵魂出窍");
		add("gui.neosim.BuildingConstructor.adjustUp","上升");
		add("gui.neosim.BuildingConstructor.adjustDown","下降");
		add("gui.neosim.BuildingConstructor.adjustMirror","镜像");
		add("gui.neosim.BuildingConstructor.adjustRotate","旋转");
		add("gui.neosim.BuildingConstructor.dirNorth","N");
		add("gui.neosim.BuildingConstructor.dirSouth","S");
		add("gui.neosim.BuildingConstructor.dirWest","W");
		add("gui.neosim.BuildingConstructor.dirEast","E");
		add("gui.neosim.BuildingConstructor.searchModeBuilding","建筑");
		add("gui.neosim.BuildingConstructor.searchModeAuthor","作者");
		add("gui.neosim.BuildingConstructor.filterAll","全部格式");
		add("gui.neosim.BuildingConstructor.filterTxt","旧格式");
		add("gui.neosim.BuildingConstructor.filterLitematic","新格式");
		add("gui.neosim.BuildingConstructor.resetView","重置视角");
		add("gui.neosim.BuildingConstructor.scanning","正在扫描箱子…");
		add("gui.neosim.BuildingConstructor.sortNameAsc","名称 ↑");
		add("gui.neosim.BuildingConstructor.sortNameDesc","名称 ↓");
		add("gui.neosim.BuildingConstructor.sortCostAsc","造价 ↑");
		add("gui.neosim.BuildingConstructor.sortCostDesc","造价 ↓");
		add("gui.neosim.BuildingConstructor.sortAuthorAsc","作者 ↑");
		add("gui.neosim.BuildingConstructor.sortAuthorDesc","作者 ↓");

		add("gui.neosim.ControlBox.title","控制箱");
		add("gui.neosim.ControlBox.building","建筑: %s");
		add("gui.neosim.ControlBox.author","作者: %s");
		add("gui.neosim.ControlBox.placer","所建玩家: %s");
		add("gui.neosim.ControlBox.residents","居民: %s");
		add("gui.neosim.ControlBox.none","无");
		add("gui.neosim.ControlBox.noRecord","无此建筑记录");
		add("gui.neosim.ControlBox.close","关闭");
		add("gui.neosim.ControlBox.evict","驱逐");
		add("gui.neosim.ControlBox.evictAll","清空全部住户");
		add("gui.neosim.ControlBox.moveIn","入住");
		add("gui.neosim.ControlBox.homelessTitle","安排入住（无家 NPC）");
		add("gui.neosim.ControlBox.noHomeless","城市里没有无家可归的 NPC");
		add("gui.neosim.ControlBox.residentsLabel","居民");
		add("gui.neosim.ControlBox.back","返回");

		add("gui.neosim.FarmingBox.title","农业盒");
		add("gui.neosim.FarmingBox.noRecord","无此工作盒记录");
		add("gui.neosim.FarmingBox.rect","田地：%s×%s");
		add("gui.neosim.FarmingBox.unbound","未绑定地块（请将盒子紧挨标记棒放置）");
		add("gui.neosim.FarmingBox.worker","农夫：%s");
		add("gui.neosim.FarmingBox.workerNone","暂无农夫");
		add("gui.neosim.FarmingBox.workerLevel","农夫等级：%s");
		add("gui.neosim.FarmingBox.hire","雇佣");
		add("gui.neosim.FarmingBox.fire","解雇 %s");
		add("gui.neosim.FarmingBox.target","目标");
		add("gui.neosim.FarmingBox.targetTitle","目标");
		add("gui.neosim.FarmingBox.targetSummary","目标：%s");
		add("gui.neosim.FarmingBox.targetNone","未设置");
		add("gui.neosim.FarmingBox.typeWHEAT","小麦");
		add("gui.neosim.FarmingBox.typeCARROT","胡萝卜");
		add("gui.neosim.FarmingBox.typePOTATO","土豆");
		add("gui.neosim.FarmingBox.livestock","牲畜");
		add("gui.neosim.FarmingBox.industryPlant","种植业");
		add("gui.neosim.FarmingBox.industryLivestock","畜牧业");
		add("gui.neosim.FarmingBox.animalCHICKEN","鸡");
		add("gui.neosim.FarmingBox.animalPIG","猪");
		add("gui.neosim.FarmingBox.animalCOW","牛");
		add("gui.neosim.FarmingBox.animalSHEEP","羊");
		add("gui.neosim.FarmingBox.apply","确认");
		add("gui.neosim.FarmingBox.pause","暂停");
		add("gui.neosim.FarmingBox.resume","继续");
		add("gui.neosim.FarmingBox.close","关闭");
		add("gui.neosim.FarmingBox.hireTitle","选择农夫");
		add("gui.neosim.FarmingBox.goBack","返回");
		add("gui.neosim.FarmingBox.state","状态：%s");
		add("gui.neosim.FarmingBox.state.idle","空闲");
		add("gui.neosim.FarmingBox.state.waitingWorker","等待农夫");
		add("gui.neosim.FarmingBox.state.workerAssigned","农夫已就位");
		add("gui.neosim.FarmingBox.state.checkingChests","检查箱子");
		add("gui.neosim.FarmingBox.state.harvest","收割中");
		add("gui.neosim.FarmingBox.state.till","翻地中");
		add("gui.neosim.FarmingBox.state.plant","种植中");
		add("gui.neosim.FarmingBox.state.waitingSeed","缺少种子");
		add("gui.neosim.FarmingBox.state.raise","畜牧中");
		add("gui.neosim.FarmingBox.state.waitingFeed","缺少饲料");
		add("gui.neosim.FarmingBox.state.waitingChest","箱子已满");
		add("gui.neosim.FarmingBox.state.depleted","已采尽");
		add("gui.neosim.FarmingBox.forestry","林业：%s");
		add("gui.neosim.FarmingBox.industryForestry","林业");
		add("gui.neosim.FarmingBox.treeOAK","橡树");
		add("gui.neosim.FarmingBox.treeBIRCH","白桦");
		add("gui.neosim.FarmingBox.treeSPRUCE","云杉");
		add("gui.neosim.FarmingBox.treeJUNGLE","丛林");
		add("gui.neosim.FarmingBox.treeACACIA","金合欢");
		add("gui.neosim.FarmingBox.treeCHERRY","樱花");
		add("gui.neosim.FarmingBox.state.chop","伐木中");
		add("gui.neosim.FarmingBox.state.waitingSapling","缺少树苗");

		add("gui.neosim.MiningBox.title","矿业盒");
		add("gui.neosim.MiningBox.noRecord","无此工作盒记录");
		add("gui.neosim.MiningBox.rect","矿区：%s×%s");
		add("gui.neosim.MiningBox.unbound","未绑定地块（请将盒子紧挨标记棒放置）");
		add("gui.neosim.MiningBox.depth","深度：挖至 y=%s");
		add("gui.neosim.MiningBox.worker","矿工：%s");
		add("gui.neosim.MiningBox.workerNone","暂无矿工");
		// 公共：工作盒雇佣页（HireListPanel）
		add("gui.neosim.hire.search","搜索名字");
		add("gui.neosim.hire.searchHint","输入名字…");
		add("gui.neosim.hire.minLevel","最小等级");
		add("gui.neosim.hire.minLevelHint","输入最小等级…");
		add("gui.neosim.hire.hireableOnly","仅可雇佣");
		add("gui.neosim.hire.prev","上一页");
		add("gui.neosim.hire.next","下一页");
		add("gui.neosim.hire.page","%s/%s");
		add("gui.neosim.hire.level","Lv.%s");
		add("gui.neosim.hire.reason.underage","未成年");
		add("gui.neosim.hire.reason.maternity","产假中");
		add("gui.neosim.hire.reason.hired","已在别处工作");
		add("gui.neosim.hire.none","没有符合条件的市民");
		add("gui.neosim.hire.back","返回");
		add("gui.neosim.BuildingConstructor.hireTitle","选择建筑师");
		add("gui.neosim.MiningBox.workerLevel","矿工等级：%s");
		add("gui.neosim.MiningBox.hire","雇佣");
		add("gui.neosim.MiningBox.fire","解雇 %s");
		add("gui.neosim.MiningBox.discards","丢弃");
		add("gui.neosim.MiningBox.catDirt","泥土/草方块");
		add("gui.neosim.MiningBox.catStone","石头/圆石");
		add("gui.neosim.MiningBox.catSand","沙子/红沙");
		add("gui.neosim.MiningBox.apply","确认");
		add("gui.neosim.MiningBox.discardTitle","丢弃过滤");
		add("gui.neosim.MiningBox.pause","暂停");
		add("gui.neosim.MiningBox.resume","继续");
		add("gui.neosim.MiningBox.close","关闭");
		add("gui.neosim.MiningBox.hireTitle","选择矿工");
		add("gui.neosim.MiningBox.goBack","返回");
		add("gui.neosim.MiningBox.state","状态：%s");
		add("gui.neosim.MiningBox.state.idle","空闲");
		add("gui.neosim.MiningBox.state.waitingWorker","等待矿工");
		add("gui.neosim.MiningBox.state.workerAssigned","矿工已就位");
		add("gui.neosim.MiningBox.state.checkingChests","检查箱子");
		add("gui.neosim.MiningBox.state.mining","采挖中");
		add("gui.neosim.MiningBox.state.waitingChest","箱子已满");
		add("gui.neosim.MiningBox.state.depleted","已采尽");

		add("entity.neo_sim.nsnpc","新模拟城市NPC");

		add("gui.neosim.npc.title","NPC");
		add("gui.neosim.npc.setSkin","设置皮肤");
		add("gui.neosim.npc.rename","重命名");
		add("gui.neosim.npc.rename.surname","姓");
		add("gui.neosim.npc.rename.givenName","名");
		add("gui.neosim.npc.rename.confirm","确认");
		add("gui.neosim.npc.rename.cancel","取消");
		add("gui.neosim.npc.back","返回");
		add("gui.neosim.npc.info.sex","性别: %s");
		add("gui.neosim.npc.info.male","男");
		add("gui.neosim.npc.info.female","女");
		add("gui.neosim.npc.info.city","城市: %s");
		add("gui.neosim.npc.info.noCity","无");
		add("gui.neosim.npc.info.age","年龄: %d");
		add("gui.neosim.npc.info.home","家: %s");
		add("gui.neosim.npc.info.noHome","无");
		add("gui.neosim.npc.info.relationship","关系: %s");
		add("gui.neosim.npc.info.single","单身");
		add("gui.neosim.npc.info.livingWithSomeone","与他人同居");
		add("gui.neosim.npc.info.maternityLeave","产假中");
		add("gui.neosim.npc.skin.prevPage","上一页");
		add("gui.neosim.npc.skin.nextPage","下一页");
		add("gui.neosim.npc.skin.openFolder","添加自定义皮肤");
		add("gui.neosim.npc.skin.searchPlayer","输入玩家名");
		add("gui.neosim.npc.skin.searchConfirm","确定");
		add("gui.neosim.npc.skin.searching","正在搜索...");
		add("gui.neosim.npc.skin.searchFailed","失败");
		add("gui.neosim.npc.family.open","族谱");
		add("gui.neosim.npc.family.father","父亲");
		add("gui.neosim.npc.family.mother","母亲");
		add("gui.neosim.npc.family.son","儿子");
		add("gui.neosim.npc.family.daughter","女儿");
		add("gui.neosim.npc.family.brother","兄弟");
		add("gui.neosim.npc.family.sister","姐妹");
		add("gui.neosim.npc.family.grandfather","祖父");
		add("gui.neosim.npc.family.grandmother","祖母");
		add("gui.neosim.npc.family.partner","配偶");
		add("gui.neosim.npc.family.fatherInLaw","配偶父亲");
		add("gui.neosim.npc.family.motherInLaw","配偶母亲");
		add("gui.neosim.npc.family.loading","加载中…");
		add("gui.neosim.npc.family.empty","暂无亲属数据");
		add("gui.neosim.npc.family.reset","复位");
		add("gui.neosim.npc.family.tooMany","亲属过多，仅显示前 50 位");

		add("config.neosim.initialCredit","初始信用点");
		add("config.neosim.initialCredit.tooltip","城市的初始信用点");
		add("config.neosim.creditsPerBlock","每方块信用点");
		add("config.neosim.creditsPerBlock.tooltip","每放置一个方块扣除的信用点");
		add("config.neosim.maxPopulation","最大人口数");
		add("config.neosim.maxPopulation.tooltip","城市的最大人口数");
		add("config.neosim.npcMinAge","NPC最小年龄");
		add("config.neosim.npcMinAge.tooltip","NPC的最小随机年龄");
		add("config.neosim.npcMaxAge","NPC最大年龄");
		add("config.neosim.npcMaxAge.tooltip","NPC的最大随机年龄");
		add("config.neosim.lifeRentDefault","住宅默认租金");
		add("config.neosim.lifeRentDefault.tooltip","每天每座有居民的住宅收取的租金，未按体积定价的记录使用此默认值");
		add("config.neosim.lifeRentPerBlock","按建筑体积定价系数");
		add("config.neosim.lifeRentPerBlock.tooltip","完工住宅按非空气方块数×该系数计算每日租金");
		add("config.neosim.lifeAdultAge","成年年龄");
		add("config.neosim.lifeAdultAge.tooltip","居民长到该年龄即成年：可被雇佣，跨过该年龄当天退父母家并开始找房子");
		add("config.neosim.lifeMaxAge","寿终年龄");
		add("config.neosim.lifeMaxAge.tooltip","超过该年龄后，居民每天有1/10概率自然寿终");
		add("config.neosim.lifeAgingAdultDay","成人每周长岁日");
		add("config.neosim.lifeAgingAdultDay.tooltip","成人每周长岁的星期");
		add("config.neosim.lifeAgingChildDays","儿童每周长岁日");
		add("config.neosim.lifeAgingChildDays.tooltip","儿童每周长岁的星期列表");
		add("config.neosim.lifeMarriageChance","结婚概率");
		add("config.neosim.lifeMarriageChance.tooltip","BESTFRIENDS满级时掷硬币结婚的概率");
		add("config.neosim.lifePregnancyDays","孕期天数");
		add("config.neosim.lifePregnancyDays.tooltip","从怀孕到分娩的天数");
		add("config.neosim.lifePregnancyChance","怀孕概率");
		add("config.neosim.lifePregnancyChance.tooltip","怀孕概率（1/7）");
		add("config.neosim.lifeRestChance","居家休息概率");
		add("config.neosim.lifeRestChance.tooltip","有家无业市民白天在家休息、不外出社交的概率");
		add("config.neosim.lifePregnancyMaxAge","受孕上限年龄");
		add("config.neosim.lifePregnancyMaxAge.tooltip","女性超过该年龄后不再参与受孕");
		add("config.neosim.lifePregnancyStartStage","受孕初始孕期进度");
		add("config.neosim.lifePregnancyStartStage.tooltip","受孕瞬间孕期进度的初始值，越高则总孕期越短");
		add("config.neosim.lifeSocialRange","社交寻找半径");
		add("config.neosim.lifeSocialRange.tooltip","无业市民白天寻找社交对象的最大距离（格）");
		add("config.neosim.lifeSocialArriveDist","社交判定范围");
		add("config.neosim.lifeSocialArriveDist.tooltip","两人相距达到该值（格）即视为到达、开始凑在一起聊天");
		add("config.neosim.lifeRelationshipDowngradeChance","关系变差概率");
		add("config.neosim.lifeRelationshipDowngradeChance.tooltip","每次社交结算时关系下降而非上升的概率");
		add("config.neosim.lifeRelationshipChangeMax","单次关系增减量上限");
		add("config.neosim.lifeRelationshipChangeMax.tooltip","每次社交结算时关系增减幅度的最大值");
		add("config.neosim.lifeMarriageSubLevel","结婚所需关系度");
		add("config.neosim.lifeMarriageSubLevel.tooltip","BESTFRIENDS 关系达到该子等级后才会触发结婚判定");
		add("config.neosim.workFarmCreditPerBlock","农业每方块信用点");
		add("config.neosim.workFarmCreditPerBlock.tooltip","农夫每收成一格作物返还的信用点");
		add("config.neosim.workFarmMaxAdults","畜牧成年上限");
		add("config.neosim.workFarmMaxAdults.tooltip","围栏内成年牲畜数超过该值即自动屠宰一只");
		add("config.neosim.workFarmMaxTotal","畜牧总量上限");
		add("config.neosim.workFarmMaxTotal.tooltip","围栏内牲畜总数达到该值即停止繁殖");
		add("config.neosim.workFarmBabyGrowMinutes","畜牧幼崽长大分钟数");
		add("config.neosim.workFarmBabyGrowMinutes.tooltip","幼崽出生后经过该分钟数即长大成年（默认5分钟）");
		add("config.neosim.workFarmBreedCooldownSeconds","畜牧繁殖冷却（秒）");
		add("config.neosim.workFarmBreedCooldownSeconds.tooltip","某物种成功繁殖后的冷却秒数（0=关闭）");
		add("config.neosim.workMineCreditPerBlock","矿业每方块信用点");
		add("config.neosim.workMineCreditPerBlock.tooltip","矿工每挖掉一格方块返还的信用点");
		add("config.neosim.workMineDiscards","矿业默认丢弃");
		add("config.neosim.workMineDiscards.tooltip","矿工默认丢弃的方块类别");

		add("neo_sim.configuration.title","%s 配置");
		add("neo_sim.configuration.section.neo.sim.toml.title","%s 通用配置");
		add("neo_sim.configuration.section.neo.sim.toml","%s 配置");
		add("neo_sim.configuration.general","通用");
		add("neo_sim.configuration.general.button","通用");
		add("neo_sim.configuration.general.tooltip","城市初始资金、建造费用、人口上限与 NPC 年龄范围");
		add("neo_sim.configuration.life","生活系统");
		add("neo_sim.configuration.life.button","生活系统");
		add("neo_sim.configuration.life.tooltip","居民生命周期相关参数：房租、衰老、作息、生育、社交、关系与婚姻");
		add("neo_sim.configuration.rent","房租与收入");
		add("neo_sim.configuration.rent.button","房租与收入");
		add("neo_sim.configuration.rent.tooltip","住宅每日收租的默认值与按建筑体积定价系数");
		add("neo_sim.configuration.aging","衰老与寿终");
		add("neo_sim.configuration.aging.button","衰老与寿终");
		add("neo_sim.configuration.aging.tooltip","成年年龄、寿终年龄与每周长岁日");
		add("neo_sim.configuration.rest","作息");
		add("neo_sim.configuration.rest.button","作息");
		add("neo_sim.configuration.rest.tooltip","有家无业市民白天居家休息概率");
		add("neo_sim.configuration.reproduction","生育与分娩");
		add("neo_sim.configuration.reproduction.button","生育与分娩");
		add("neo_sim.configuration.reproduction.tooltip","孕期天数、怀孕概率、受孕上限年龄与初始孕期进度");
		add("neo_sim.configuration.social","社交与串门");
		add("neo_sim.configuration.social.button","社交与串门");
		add("neo_sim.configuration.social.tooltip","无业市民白天社交的寻找半径与到达判定距离");
		add("neo_sim.configuration.relationship","关系增减");
		add("neo_sim.configuration.relationship.button","关系增减");
		add("neo_sim.configuration.relationship.tooltip","每次社交结算时关系变差概率与增减量上限");
		add("neo_sim.configuration.marriage","婚姻");
		add("neo_sim.configuration.marriage.button","婚姻");
		add("neo_sim.configuration.marriage.tooltip","结婚概率与结婚所需关系度");
		add("neo_sim.configuration.workplot","农业与矿业");
		add("neo_sim.configuration.workplot.button","农业与矿业");
		add("neo_sim.configuration.workplot.tooltip","工作盒绑定半径、农业/矿业每方块信用点");
	}
}
