package com.wenzai.neosim.datagen;

import com.wenzai.neosim.NeoSim;
import com.wenzai.neosim.block.ModBlocks;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class LangEnUs extends LanguageProvider
{
	public LangEnUs(PackOutput output)
	{
		super(output, NeoSim.MOD_ID, "en_us");
	}

	@Override
	protected void addTranslations()
	{
		add(ModBlocks.BUILDING_CONSTRUCTOR.get(), "Building Constructor");
		add(ModBlocks.CONTROL_BOX.get(), "Control Box");
		add(ModBlocks.MARKER.get(), "Marker");
		add(ModBlocks.FARMING_BOX.get(),  "Farming Box");
		add(ModBlocks.MINING_BOX.get(), "Mining Box");
		add(ModBlocks.DELIVERY_BOX.get(), "Delivery Box");
		add(ModBlocks.LIVING_POINT.get(), "Living Point");

		add("gui.neosim.DeliveryBox.title","Delivery Box");
		add("gui.neosim.DeliveryBox.worker","Courier: %s");
		add("gui.neosim.DeliveryBox.workerNone","No courier");
		add("gui.neosim.DeliveryBox.workerLevel","Courier level: %s");
		add("gui.neosim.DeliveryBox.hire","Hire");
		add("gui.neosim.DeliveryBox.fire","Fire");
		add("gui.neosim.DeliveryBox.pause","Pause");
		add("gui.neosim.DeliveryBox.resume","Resume");
		add("gui.neosim.DeliveryBox.close","Close");
		add("gui.neosim.DeliveryBox.hireTitle","Choose a courier");
		add("gui.neosim.DeliveryBox.goBack","Back");
		add("gui.neosim.DeliveryBox.state","Status: %s");
		add("gui.neosim.DeliveryBox.state.idle","Idle");
		add("gui.neosim.DeliveryBox.state.waitingWorker","Waiting for courier");
		add("gui.neosim.DeliveryBox.state.workerAssigned","Courier assigned");
		add("gui.neosim.DeliveryBox.state.walking","Delivering");
		add("gui.neosim.DeliveryBox.state.depositing","Depositing");
		add("gui.neosim.DeliveryBox.state.returning","Returning");

		add("config.neosim.deliveryCreditPerUnit","Credit per item delivered");
		add("config.neosim.deliveryChunkRadius","Courier chunk window radius");
		add("neo_sim.configuration.delivery","Delivery");
		add("neo_sim.configuration.delivery.button","Delivery");
		add("neo_sim.configuration.delivery.tooltip","Per-item delivery cost and courier chunk window radius");

		add("itemGroup.neosim_tab","Neo-Sim");

		add("gui.neosim.run.title","Run");
		add("gui.neosim.run.buttonNormal","Normal Mode");
		add("gui.neosim.run.buttonCreative","Creative Mode");
		add("gui.neosim.run.buttonHardcore","Hardcore Mode");
		add("gui.neosim.run.buttonClose","Close");
		add("gui.neosim.run.tipNormal","Author doesn't know what will happen:)");
		add("gui.neosim.run.tipCreative","Unlimited funds and resources");
		add("gui.neosim.run.tipHardcore","Buildings require all blocks");

		add("gui.neosim.hud.population","population");
		add("gui.neosim.hud.day","Day %s");
		add("gui.neosim.hud.credit","credit");
		add("gui.neosim.hud.monday","Monday");
		add("gui.neosim.hud.tuesday","Tuesday");
		add("gui.neosim.hud.wednesday","Wednesday");
		add("gui.neosim.hud.thursday","Thursday");
		add("gui.neosim.hud.friday","Friday");
		add("gui.neosim.hud.saturday","Saturday");
		add("gui.neosim.hud.sunday","Sunday");

		add("gui.neosim.city.title","City");
		add("gui.neosim.city.add","Add City");
		add("gui.neosim.city.choose","Choose City");
		add("gui.neosim.city.refresh","Refresh List");
		add("gui.neosim.city.buttonConfirm","OK");

		add("gui.neosim.BuildingConstructor.title","Building Constructor");
		add("gui.neosim.BuildingConstructor.statusReady","Status: Ready");
		add("gui.neosim.BuildingConstructor.page0.hint","Please choose a task for this building constructor");
		add("gui.neosim.BuildingConstructor.page1.hint","Please choose a type of building");
		add("gui.neosim.BuildingConstructor.page2.hint","Choose a residential building");
		add("gui.neosim.BuildingConstructor.page3.hint","Choose a commercial building");
		add("gui.neosim.BuildingConstructor.page4.hint","Choose an industrial building");
		add("gui.neosim.BuildingConstructor.page5.hint","Choose an other type building");
		add("gui.neosim.BuildingConstructor.page6.hint","Building requirements for %s");
		add("gui.neosim.BuildingConstructor.hireBuilder","Hire");
		add("gui.neosim.BuildingConstructor.fireWorker","Fire %s");
		add("gui.neosim.BuildingConstructor.chooseBuilding","Choose building");
		add("gui.neosim.BuildingConstructor.currentStatus","Current Status");
		add("gui.neosim.BuildingConstructor.continue","Continue");
		add("gui.neosim.BuildingConstructor.pause","Pause");
		add("gui.neosim.BuildingConstructor.choosePlan","Choose plan");
		add("gui.neosim.BuildingConstructor.currentMissing","Currently Missing");
		add("gui.neosim.BuildingConstructor.page11.hint","Choose a terraform plan");
		add("gui.neosim.BuildingConstructor.plan.FLATTEN","Flatten");
		add("gui.neosim.BuildingConstructor.plan.FLATTEN.desc","Mine terrain blocks above the baseline; drops go to chests");
		add("gui.neosim.BuildingConstructor.plan.VALUE_PACK","Dirt pack");
		add("gui.neosim.BuildingConstructor.plan.VALUE_PACK.desc","Lay a single layer of dirt at the baseline");
		add("gui.neosim.BuildingConstructor.plan.GRASS_PACK","Grass pack");
		add("gui.neosim.BuildingConstructor.plan.GRASS_PACK.desc","Lay a single layer of grass blocks at the baseline");
		add("gui.neosim.BuildingConstructor.plan.SEALAND","Fill water");
		add("gui.neosim.BuildingConstructor.plan.SEALAND.desc","Fill water columns with dirt from bottom to top");
		add("gui.neosim.BuildingConstructor.plan.LAWNMOWER","Mow grass");
		add("gui.neosim.BuildingConstructor.plan.LAWNMOWER.desc","Clear grass and flowers; drops go to chests");
		add("gui.neosim.BuildingConstructor.plan.NATURE","Plant trees");
		add("gui.neosim.BuildingConstructor.plan.NATURE.desc","Plant saplings and flowers (1 sapling per 15 blocks)");
		add("gui.neosim.BuildingConstructor.plan.DEICER","Remove snow");
		add("gui.neosim.BuildingConstructor.plan.DEICER.desc","Clear snow layers");
		add("gui.neosim.BuildingConstructor.noArchitect","Hire an architect first");
		add("gui.neosim.BuildingConstructor.confirmTerraform","Confirm terraform");
		add("gui.neosim.BuildingConstructor.terraformRate","$ %s per block");
		add("gui.neosim.BuildingConstructor.typeResidential","Residential");
		add("gui.neosim.BuildingConstructor.typeCommercial","Commercial");
		add("gui.neosim.BuildingConstructor.typeIndustrial","Industrial");
		add("gui.neosim.BuildingConstructor.typeOther","Other");
		add("gui.neosim.BuildingConstructor.typeCustom","Custom");
		add("gui.neosim.BuildingConstructor.page9.hint","Choose a custom building");
		add("gui.neosim.BuildingConstructor.page10.hint","Currently Missing Materials for %s");
		add("gui.neosim.BuildingConstructor.add","Add Custom Building");
		add("gui.neosim.BuildingConstructor.search","Search");
		add("gui.neosim.BuildingConstructor.prevPage","< Page");
		add("gui.neosim.BuildingConstructor.nextPage","Page >");
		add("gui.neosim.BuildingConstructor.goBack","Go Back");
		add("gui.neosim.BuildingConstructor.preview","Preview");
		add("gui.neosim.BuildingConstructor.previewAdjust","Adjust Preview");
		add("gui.neosim.BuildingConstructor.refresh","Refresh");
		add("gui.neosim.BuildingConstructor.buildIt","Build it!");
		add("gui.neosim.BuildingConstructor.rotateBlockOrientation","Rotate Block Orientation");
		add("gui.neosim.BuildingConstructor.oldBlueprintWarning","You are using an old-version blueprint. Please check whether the block orientation is wrong.");
		add("gui.neosim.BuildingConstructor.dimensions","Dimensions: %s");
		add("gui.neosim.BuildingConstructor.cost","$ %s");
		add("gui.neosim.BuildingConstructor.totalBlocks","Total blocks: %s");
		add("gui.neosim.BuildingConstructor.blocks","%s blocks");
		add("gui.neosim.BuildingConstructor.noMaterials","No materials required (empty building)");
		add("gui.neosim.BuildingConstructor.noMaterialsCreative","Creative mode: all blocks free, no materials required");
		add("gui.neosim.BuildingConstructor.materials","Materials: %s block types");
		add("gui.neosim.BuildingConstructor.moreTypes","  ...and %s more types");
		add("gui.neosim.BuildingConstructor.missingCount","Missing %s material types");
		add("gui.neosim.BuildingConstructor.missingLine","Missing %s");
		add("gui.neosim.BuildingConstructor.missingNone","All materials available, nothing missing");
		add("gui.neosim.BuildingConstructor.unknownAuthor","Unknown");
		add("gui.neosim.BuildingConstructor.page8.hint","Current Build Status");
		add("gui.neosim.BuildingConstructor.statusBuilding","Target Building:");
		add("gui.neosim.BuildingConstructor.statusBuilder","Assigned Builder:");
		add("gui.neosim.BuildingConstructor.statusState","Build State:");
		add("gui.neosim.BuildingConstructor.statusProgress","Progress: %s / %s");
		add("gui.neosim.BuildingConstructor.statusMaterials","Current Missing Material:");
		add("gui.neosim.BuildingConstructor.statusNone","None");
		add("gui.neosim.BuildingConstructor.statusState.idle","Idle");
		add("gui.neosim.BuildingConstructor.statusState.waitingWorker","Waiting for Worker");
		add("gui.neosim.BuildingConstructor.statusState.workerAssigned","Worker Assigned");
		add("gui.neosim.BuildingConstructor.statusState.loading","Loading Blueprint");
		add("gui.neosim.BuildingConstructor.statusState.waiting","Waiting for Resources");
		add("gui.neosim.BuildingConstructor.statusState.building","Building");
		add("gui.neosim.BuildingConstructor.statusState.complete","Complete");
		add("gui.neosim.BuildingConstructor.builderLevel","Builder Lv.%s");
		add("gui.neosim.BuildingConstructor.soulOut","Soul Out");
		add("gui.neosim.BuildingConstructor.adjustUp","Up");
		add("gui.neosim.BuildingConstructor.adjustDown","Down");
		add("gui.neosim.BuildingConstructor.adjustMirror","Mirror");
		add("gui.neosim.BuildingConstructor.adjustRotate","Rotate");
		add("gui.neosim.BuildingConstructor.dirNorth","N");
		add("gui.neosim.BuildingConstructor.dirSouth","S");
		add("gui.neosim.BuildingConstructor.dirWest","W");
		add("gui.neosim.BuildingConstructor.dirEast","E");
		add("gui.neosim.BuildingConstructor.searchModeBuilding","Building");
		add("gui.neosim.BuildingConstructor.searchModeAuthor","Author");
		add("gui.neosim.BuildingConstructor.filterAll","All Formats");
		add("gui.neosim.BuildingConstructor.filterTxt","Old Format");
		add("gui.neosim.BuildingConstructor.filterLitematic","New Format");
		add("gui.neosim.BuildingConstructor.resetView","Reset View");
		add("gui.neosim.BuildingConstructor.scanning","Scanning chests...");
		add("gui.neosim.BuildingConstructor.sortNameAsc","Name ↑");
		add("gui.neosim.BuildingConstructor.sortNameDesc","Name ↓");
		add("gui.neosim.BuildingConstructor.sortCostAsc","Cost ↑");
		add("gui.neosim.BuildingConstructor.sortCostDesc","Cost ↓");
		add("gui.neosim.BuildingConstructor.sortAuthorAsc","Author ↑");
		add("gui.neosim.BuildingConstructor.sortAuthorDesc","Author ↓");

		add("gui.neosim.ControlBox.title","Control Box");
		add("gui.neosim.ControlBox.building","Building: %s");
		add("gui.neosim.ControlBox.author","Author: %s");
		add("gui.neosim.ControlBox.placer","Built by: %s");
		add("gui.neosim.ControlBox.residents","Residents: %s");
		add("gui.neosim.ControlBox.none","None");
		add("gui.neosim.ControlBox.noRecord","No record for this building");
		add("gui.neosim.ControlBox.close","Close");
		add("gui.neosim.ControlBox.evict","Evict");
		add("gui.neosim.ControlBox.evictAll","Evict All");
		add("gui.neosim.ControlBox.moveIn","Move In");
		add("gui.neosim.ControlBox.homelessTitle","Move In (Homeless)");
		add("gui.neosim.ControlBox.noHomeless","No homeless NPCs in the city");
		add("gui.neosim.ControlBox.residentsLabel","Residents");
		add("gui.neosim.ControlBox.back","Back");

		add("gui.neosim.FarmingBox.title","Farming Box");
		add("gui.neosim.FarmingBox.noRecord","No work box record");
		add("gui.neosim.FarmingBox.rect","Farm: %s×%s");
		add("gui.neosim.FarmingBox.unbound","Not bound (place the box next to a marker stick)");
		add("gui.neosim.FarmingBox.worker","Farmer: %s");
		add("gui.neosim.FarmingBox.workerNone","No farmer");
		add("gui.neosim.FarmingBox.workerLevel","Farmer level: %s");
		add("gui.neosim.FarmingBox.hire","Hire");
		add("gui.neosim.FarmingBox.fire","Fire %s");
		add("gui.neosim.FarmingBox.target","Target");
		add("gui.neosim.FarmingBox.targetTitle","Target");
		add("gui.neosim.FarmingBox.targetSummary","Target: %s");
		add("gui.neosim.FarmingBox.targetNone","Not set");
		add("gui.neosim.FarmingBox.typeWHEAT","Wheat");
		add("gui.neosim.FarmingBox.typeCARROT","Carrot");
		add("gui.neosim.FarmingBox.typePOTATO","Potato");
		add("gui.neosim.FarmingBox.useBoneMeal","Use Bone Meal");
		add("gui.neosim.FarmingBox.livestock","Livestock");
		add("gui.neosim.FarmingBox.industryPlant","Planting");
		add("gui.neosim.FarmingBox.industryLivestock","Livestock");
		add("gui.neosim.FarmingBox.animalCHICKEN","Chicken");
		add("gui.neosim.FarmingBox.animalPIG","Pig");
		add("gui.neosim.FarmingBox.animalCOW","Cow");
		add("gui.neosim.FarmingBox.animalSHEEP","Sheep");
		add("gui.neosim.FarmingBox.apply","Apply");
		add("gui.neosim.FarmingBox.pause","Pause");
		add("gui.neosim.FarmingBox.resume","Resume");
		add("gui.neosim.FarmingBox.close","Close");
		add("gui.neosim.FarmingBox.hireTitle","Choose a farmer");
		add("gui.neosim.FarmingBox.goBack","Back");
		add("gui.neosim.FarmingBox.state","Status: %s");
		add("gui.neosim.FarmingBox.state.idle","Idle");
		add("gui.neosim.FarmingBox.state.waitingWorker","Waiting for farmer");
		add("gui.neosim.FarmingBox.state.workerAssigned","Farmer assigned");
		add("gui.neosim.FarmingBox.state.checkingChests","Checking chests");
		add("gui.neosim.FarmingBox.state.harvest","Harvesting");
		add("gui.neosim.FarmingBox.state.till","Tilling");
		add("gui.neosim.FarmingBox.state.plant","Planting");
		add("gui.neosim.FarmingBox.state.waitingSeed","No seeds");
		add("gui.neosim.FarmingBox.state.raise","Raising livestock");
		add("gui.neosim.FarmingBox.state.waitingFeed","No feed");
		add("gui.neosim.FarmingBox.state.waitingChest","Chest full");
		add("gui.neosim.FarmingBox.state.depleted","Exhausted");
		add("gui.neosim.FarmingBox.forestry","Forestry: %s");
		add("gui.neosim.FarmingBox.industryForestry","Forestry");
		add("gui.neosim.FarmingBox.treeOAK","Oak");
		add("gui.neosim.FarmingBox.treeBIRCH","Birch");
		add("gui.neosim.FarmingBox.treeSPRUCE","Spruce");
		add("gui.neosim.FarmingBox.treeJUNGLE","Jungle");
		add("gui.neosim.FarmingBox.treeACACIA","Acacia");
		add("gui.neosim.FarmingBox.treeCHERRY","Cherry");
		add("gui.neosim.FarmingBox.state.chop","Chopping");
		add("gui.neosim.FarmingBox.state.waitingSapling","No saplings");

		add("gui.neosim.MiningBox.title","Mining Box");
		add("gui.neosim.MiningBox.noRecord","No work box record");
		add("gui.neosim.MiningBox.rect","Mine: %s×%s");
		add("gui.neosim.MiningBox.unbound","Not bound (place the box next to a marker stick)");
		add("gui.neosim.MiningBox.depth","Depth: mine down to y=%s");
		add("gui.neosim.MiningBox.worker","Miner: %s");
		add("gui.neosim.MiningBox.workerNone","No miner");

		add("gui.neosim.hire.search","Search name");
		add("gui.neosim.hire.searchHint","Type a name…");
		add("gui.neosim.hire.minLevel","Min level");
		add("gui.neosim.hire.minLevelHint","Type a min level…");
		add("gui.neosim.hire.hireableOnly","Hireable only");
		add("gui.neosim.hire.prev","Prev");
		add("gui.neosim.hire.next","Next");
		add("gui.neosim.hire.page","%s/%s");
		add("gui.neosim.hire.level","Lv.%s");
		add("gui.neosim.hire.reason.underage","Underage");
		add("gui.neosim.hire.reason.maternity","On leave");
		add("gui.neosim.hire.reason.hired","Working elsewhere");
		add("gui.neosim.hire.none","No matching citizens");
		add("gui.neosim.hire.back","Back");
		add("gui.neosim.BuildingConstructor.hireTitle","Choose an architect");
		add("gui.neosim.MiningBox.workerLevel","Miner level: %s");
		add("gui.neosim.MiningBox.hire","Hire");
		add("gui.neosim.MiningBox.fire","Fire %s");
		add("gui.neosim.MiningBox.discards","Discard");
		add("gui.neosim.MiningBox.catDirt","Dirt/grass");
		add("gui.neosim.MiningBox.catStone","Stone/cobble");
		add("gui.neosim.MiningBox.catSand","Sand/red sand");
		add("gui.neosim.MiningBox.apply","Apply");
		add("gui.neosim.MiningBox.discardTitle","Discard Filter");
		add("gui.neosim.MiningBox.pause","Pause");
		add("gui.neosim.MiningBox.resume","Resume");
		add("gui.neosim.MiningBox.close","Close");
		add("gui.neosim.MiningBox.hireTitle","Choose a miner");
		add("gui.neosim.MiningBox.goBack","Back");
		add("gui.neosim.MiningBox.state","Status: %s");
		add("gui.neosim.MiningBox.state.idle","Idle");
		add("gui.neosim.MiningBox.state.waitingWorker","Waiting for miner");
		add("gui.neosim.MiningBox.state.workerAssigned","Miner assigned");
		add("gui.neosim.MiningBox.state.checkingChests","Checking chests");
		add("gui.neosim.MiningBox.state.mining","Mining");
		add("gui.neosim.MiningBox.state.waitingChest","Chest full");
		add("gui.neosim.MiningBox.state.depleted","Exhausted");

		add("entity.neo_sim.nsnpc","NSnpc");

		add("gui.neosim.npc.title","NPC");
		add("gui.neosim.npc.setSkin","Set Skin");
		add("gui.neosim.npc.rename","Rename");
		add("gui.neosim.npc.rename.surname","Surname");
		add("gui.neosim.npc.rename.givenName","Given Name");
		add("gui.neosim.npc.rename.confirm","Confirm");
		add("gui.neosim.npc.rename.cancel","Cancel");
		add("gui.neosim.npc.back","Back");
		add("gui.neosim.npc.info.sex","Sex: %s");
		add("gui.neosim.npc.info.male","Male");
		add("gui.neosim.npc.info.female","Female");
		add("gui.neosim.npc.info.city","City: %s");
		add("gui.neosim.npc.info.noCity","None");
		add("gui.neosim.npc.info.age","Age: %d");
		add("gui.neosim.npc.info.home","Home: %s");
		add("gui.neosim.npc.info.noHome","None");
		add("gui.neosim.npc.info.relationship","Relationship: %s");
		add("gui.neosim.npc.info.single","Single");
		add("gui.neosim.npc.info.livingWithSomeone","Living with someone");
		add("gui.neosim.npc.info.maternityLeave","On Maternity Leave");
		add("gui.neosim.npc.skin.prevPage","Previous");
		add("gui.neosim.npc.skin.nextPage","Next");
		add("gui.neosim.npc.skin.openFolder","Add Custom Skin");
		add("gui.neosim.npc.skin.searchPlayer","Enter Player Name");
		add("gui.neosim.npc.skin.searchConfirm","OK");
		add("gui.neosim.npc.skin.searching","Searching...");
		add("gui.neosim.npc.skin.searchFailed","Failed");
		add("gui.neosim.npc.family.open","Family");
		add("gui.neosim.npc.family.father","Father");
		add("gui.neosim.npc.family.mother","Mother");
		add("gui.neosim.npc.family.son","Son");
		add("gui.neosim.npc.family.daughter","Daughter");
		add("gui.neosim.npc.family.brother","Brother");
		add("gui.neosim.npc.family.sister","Sister");
		add("gui.neosim.npc.family.grandfather","Grandfather");
		add("gui.neosim.npc.family.grandmother","Grandmother");
		add("gui.neosim.npc.family.partner","Partner");
		add("gui.neosim.npc.family.fatherInLaw","Father-in-law");
		add("gui.neosim.npc.family.motherInLaw","Mother-in-law");
		add("gui.neosim.npc.family.loading","Loading…");
		add("gui.neosim.npc.family.empty","No family data");
		add("gui.neosim.npc.family.reset","Reset");
		add("gui.neosim.npc.family.tooMany","Too many relatives, showing first 50");

		add("config.neosim.initialCredit","Initial Credit");
		add("config.neosim.initialCredit.tooltip","Initial credit points for the city");
		add("config.neosim.creditsPerBlock","Credits Per Block");
		add("config.neosim.creditsPerBlock.tooltip","Credit points deducted per block placed (not in Creative mode)");
		add("config.neosim.maxPopulation","Max Population");
		add("config.neosim.maxPopulation.tooltip","Maximum population of the city");
		add("config.neosim.npcMinAge","NPC Min Age");
		add("config.neosim.npcMinAge.tooltip","Minimum random age of NPCs");
		add("config.neosim.npcMaxAge","NPC Max Age");
		add("config.neosim.npcMaxAge.tooltip","Maximum random age of NPCs");
		add("config.neosim.lifeRentDefault","Residential Rent Default");
		add("config.neosim.lifeRentDefault.tooltip","Daily rent charged per occupied residential building; fallback for records without volume-based rent");
		add("config.neosim.lifeRentPerBlock","Rent Per Block");
		add("config.neosim.lifeRentPerBlock.tooltip","Completed residences charge daily rent = non-air block count × this multiplier");
		add("config.neosim.lifeAdultAge","Adult Age");
		add("config.neosim.lifeAdultAge.tooltip","Age at which residents become adults: hireable and leave home (parent home released the day they cross it)");
		add("config.neosim.lifeMaxAge","Max Age");
		add("config.neosim.lifeMaxAge.tooltip","Past this age, residents have a 1/10 chance per day to die of old age");
		add("config.neosim.lifeAgingAdultDay","Adult Aging Day");
		add("config.neosim.lifeAgingAdultDay.tooltip","Day of week adults age");
		add("config.neosim.lifeAgingChildDays","Child Aging Days");
		add("config.neosim.lifeAgingChildDays.tooltip","Days of week children age");
		add("config.neosim.lifeMarriageChance","Marriage Chance");
		add("config.neosim.lifeMarriageChance.tooltip","Chance for maxed BESTFRIENDS couples to marry on coin flip");
		add("config.neosim.lifePregnancyDays","Pregnancy Days");
		add("config.neosim.lifePregnancyDays.tooltip","Days from conception to birth");
		add("config.neosim.lifePregnancyChance","Pregnancy Chance");
		add("config.neosim.lifePregnancyChance.tooltip","Pregnancy Chance (1/7)");
		add("config.neosim.lifeRestChance","Rest at Home Chance");
		add("config.neosim.lifeRestChance.tooltip","Chance for jobless residents with a home to rest at home instead of socializing during the day");
		add("config.neosim.lifePregnancyMaxAge","Pregnancy Max Age");
		add("config.neosim.lifePregnancyMaxAge.tooltip","Maximum age at which a female resident can become pregnant");
		add("config.neosim.lifePregnancyStartStage","Pregnancy Start Stage");
		add("config.neosim.lifePregnancyStartStage.tooltip","Initial pregnancy stage at conception; higher values shorten the total pregnancy");
		add("config.neosim.lifeSocialRange","Social Search Range");
		add("config.neosim.lifeSocialRange.tooltip","Maximum distance (blocks) in which jobless residents look for someone to socialize with during the day");
		add("config.neosim.lifeSocialArriveDist","Social Arrive Distance");
		add("config.neosim.lifeSocialArriveDist.tooltip","Distance (blocks) at which two residents are considered to have met and start chatting");
		add("config.neosim.lifeRelationshipDowngradeChance","Relationship Downgrade Chance");
		add("config.neosim.lifeRelationshipDowngradeChance.tooltip","Chance that a relationship worsens rather than improves on each social interaction");
		add("config.neosim.lifeRelationshipChangeMax","Relationship Change Max");
		add("config.neosim.lifeRelationshipChangeMax.tooltip","Maximum magnitude by which a relationship can change per social interaction");
		add("config.neosim.lifeMarriageSubLevel","Marriage Sub-level");
		add("config.neosim.lifeMarriageSubLevel.tooltip","Sub-level a BESTFRIENDS relationship must reach before marriage can be triggered");
		add("config.neosim.workFarmCreditPerBlock","Farm credits per block");
		add("config.neosim.workFarmCreditPerBlock.tooltip","Credits refunded per crop harvested by a farmer");
		add("config.neosim.workFarmMaxAdults","Livestock max adults");
		add("config.neosim.workFarmMaxAdults.tooltip","Slaughter one adult when adult livestock in the pen exceeds this");
		add("config.neosim.workFarmMaxTotal","Livestock max total");
		add("config.neosim.workFarmMaxTotal.tooltip","Stop breeding when total livestock in the pen reaches this");
		add("config.neosim.workFarmBabyGrowMinutes","Livestock baby grow minutes");
		add("config.neosim.workFarmBabyGrowMinutes.tooltip","Minutes for newborn livestock to grow up (default 5)");
		add("config.neosim.workFarmBreedCooldownSeconds","Livestock breed cooldown (s)");
		add("config.neosim.workFarmBreedCooldownSeconds.tooltip","Cooldown seconds after a species successfully breeds (0 = off)");
		add("config.neosim.workMineCreditPerBlock","Mine credits per block");
		add("config.neosim.workMineCreditPerBlock.tooltip","Credits refunded per block mined by a miner");
		add("config.neosim.workMineDiscards","Mine default discards");
		add("config.neosim.workMineDiscards.tooltip","Discard categories a miner drops by default");

		add("neo_sim.configuration.title","%s Configuration");
		add("neo_sim.configuration.section.neo.sim.toml.title","%s Common Configuration");
		add("neo_sim.configuration.section.neo.sim.toml","%s Configuration");
		add("neo_sim.configuration.general","General");
		add("neo_sim.configuration.general.button","General");
		add("neo_sim.configuration.general.tooltip","City initial credit, build cost, population cap and NPC age range");
		add("neo_sim.configuration.life","Life System");
		add("neo_sim.configuration.life.button","Life System");
		add("neo_sim.configuration.life.tooltip","Resident lifecycle parameters: rent, aging, rest, reproduction, social, relationship and marriage");
		add("neo_sim.configuration.rent","Rent & Income");
		add("neo_sim.configuration.rent.button","Rent & Income");
		add("neo_sim.configuration.rent.tooltip","Default daily rent and volume-based pricing multiplier for residences");
		add("neo_sim.configuration.aging","Aging & Death");
		add("neo_sim.configuration.aging.button","Aging & Death");
		add("neo_sim.configuration.aging.tooltip","Adult age, max age and weekly aging days");
		add("neo_sim.configuration.rest","Rest Schedule");
		add("neo_sim.configuration.rest.button","Rest Schedule");
		add("neo_sim.configuration.rest.tooltip","Chance for jobless residents with a home to rest at home during the day");
		add("neo_sim.configuration.reproduction","Reproduction");
		add("neo_sim.configuration.reproduction.button","Reproduction");
		add("neo_sim.configuration.reproduction.tooltip","Pregnancy days, chance, max age and initial pregnancy stage");
		add("neo_sim.configuration.social","Social & Visiting");
		add("neo_sim.configuration.social.button","Social & Visiting");
		add("neo_sim.configuration.social.tooltip","Search range and arrive distance for jobless residents socializing during the day");
		add("neo_sim.configuration.relationship","Relationship Change");
		add("neo_sim.configuration.relationship.button","Relationship Change");
		add("neo_sim.configuration.relationship.tooltip","Downgrade chance and max change per social interaction");
		add("neo_sim.configuration.marriage","Marriage");
		add("neo_sim.configuration.marriage.button","Marriage");
		add("neo_sim.configuration.marriage.tooltip","Marriage chance and required relationship sub-level");
		add("neo_sim.configuration.workplot","Farming & Mining");
		add("neo_sim.configuration.workplot.button","Farming & Mining");
		add("neo_sim.configuration.workplot.tooltip","Work box bind radius and credits per block for farming and mining");
	}
}
