package com.wenzai.neosim.datagen;

import com.wenzai.neosim.NeoSim;
import com.wenzai.neosim.block.ModBlocks;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class LangZhCn extends LanguageProvider
{
    public LangZhCn(PackOutput output)
    {
        super(output, NeoSim.MOD_ID, "zh_cn");
    }

    @Override
    protected void addTranslations()
    {
        add(ModBlocks.BUILDING_CONSTRUCTOR.get(), "建筑模盒");
        add(ModBlocks.CONTROL_BOX.get(), "控制箱");
        add(ModBlocks.MARKER.get(), "标记棒");
        add(ModBlocks.FARMING_BOX.get(), "农业盒");
        add(ModBlocks.MINING_BOX.get(), "矿业盒");
        add(ModBlocks.DELIVERY_BOX.get(), "快递盒");

        add("itemGroup.neosim_tab","新模拟城市");

        add("gui.neosim.run.title","运行");
        add("gui.neosim.run.buttonNormal","普通模式");
        add("gui.neosim.run.buttonCreative","创造模式");
        add("gui.neosim.run.buttonHardcore","硬核模式");
        add("gui.neosim.run.buttonClose","确定");
        add("gui.neosim.run.tipNormal","还没想好要写什么");
        add("gui.neosim.run.tipCreative","无限资金和资源");
        add("gui.neosim.run.tipHardcore","建筑需要所有方块");

        add("gui.neosim.hud.population","人口");
        add("gui.neosim.hud.day","第%s天");
        add("gui.neosim.hud.credit","资金");
        add("gui.neosim.hud.monday","星期一");
        add("gui.neosim.hud.tuesday","星期二");
        add("gui.neosim.hud.wednesday","星期三");
        add("gui.neosim.hud.thursday","星期四");
        add("gui.neosim.hud.friday","星期五");
        add("gui.neosim.hud.saturday","星期六");
        add("gui.neosim.hud.sunday","星期日");

        add("gui.neosim.city.title","城市");
        add("gui.neosim.city.add","新增城市");
        add("gui.neosim.city.choose","选择城市");
        add("gui.neosim.city.buttonConfirm","确定");

        add("gui.neosim.BuildingConstructor.title","建筑模盒");
        add("gui.neosim.BuildingConstructor.statusReady","状态: 就绪");
        add("gui.neosim.BuildingConstructor.page0.hint","请为建筑模盒选择一个任务");
        add("gui.neosim.BuildingConstructor.page1.hint","请选择一种建筑类型");
        add("gui.neosim.BuildingConstructor.page2.hint","选择一个住宅建筑");
        add("gui.neosim.BuildingConstructor.page3.hint","选择一个商业建筑");
        add("gui.neosim.BuildingConstructor.page4.hint","选择一个工业建筑");
        add("gui.neosim.BuildingConstructor.page5.hint","选择其他类型建筑");
        add("gui.neosim.BuildingConstructor.page6.hint","建筑需求: %s");
        add("gui.neosim.BuildingConstructor.hireBuilder","雇佣工人");
        add("gui.neosim.BuildingConstructor.fireWorker","解雇 %s");
        add("gui.neosim.BuildingConstructor.chooseBuilding","选择建筑");
        add("gui.neosim.BuildingConstructor.buildingPreview","等待更新");
        add("gui.neosim.BuildingConstructor.currentStatus","当前状态");
        add("gui.neosim.BuildingConstructor.continue","继续");
        add("gui.neosim.BuildingConstructor.pause","暂停");
        add("gui.neosim.BuildingConstructor.choosePlan","选择规划");
        add("gui.neosim.BuildingConstructor.moveBuilding","等待更新");
        add("gui.neosim.BuildingConstructor.typeResidential","住宅");
        add("gui.neosim.BuildingConstructor.typeCommercial","商业");
        add("gui.neosim.BuildingConstructor.typeIndustrial","工业");
        add("gui.neosim.BuildingConstructor.typeOther","其他");
        add("gui.neosim.BuildingConstructor.typeCustom","自定义");
        add("gui.neosim.BuildingConstructor.page9.hint","选择一个自定义建筑");
        add("gui.neosim.BuildingConstructor.add","添加自定义建筑");
        add("gui.neosim.BuildingConstructor.search","搜索");
        add("gui.neosim.BuildingConstructor.prevPage","上一页");
        add("gui.neosim.BuildingConstructor.nextPage","下一页");
        add("gui.neosim.BuildingConstructor.goBack","返回");
        add("gui.neosim.BuildingConstructor.preview","预览");
        add("gui.neosim.BuildingConstructor.previewAdjust","调整预览");
        add("gui.neosim.BuildingConstructor.buildIt","立即建造!");
        add("gui.neosim.BuildingConstructor.dimensions","尺寸: %s");
        add("gui.neosim.BuildingConstructor.cost","$ %s");
        add("gui.neosim.BuildingConstructor.totalBlocks","方块总数: %s");
        add("gui.neosim.BuildingConstructor.blocks","%s 个方块");
        add("gui.neosim.BuildingConstructor.noMaterials","无需材料 (空建筑)");
        add("gui.neosim.BuildingConstructor.noMaterialsCreative","创造模式：全部方块免费，无需材料");
        add("gui.neosim.BuildingConstructor.materials","材料: %s 种方块");
        add("gui.neosim.BuildingConstructor.moreTypes","  ...还有 %s 种");
        add("gui.neosim.BuildingConstructor.unknownAuthor","未知");
        add("gui.neosim.BuildingConstructor.page8.hint","当前建造状态");
        add("gui.neosim.BuildingConstructor.statusBuilding","目标建筑:");
        add("gui.neosim.BuildingConstructor.statusBuilder","所选建筑师:");
        add("gui.neosim.BuildingConstructor.statusState","建造状态:");
        add("gui.neosim.BuildingConstructor.statusProgress","进度: %s / %s");
        add("gui.neosim.BuildingConstructor.statusMaterials","当前所需方块:");
        add("gui.neosim.BuildingConstructor.statusNone","无");
        add("gui.neosim.BuildingConstructor.statusState.idle","空闲");
        add("gui.neosim.BuildingConstructor.statusState.waitingWorker","等待工人");
        add("gui.neosim.BuildingConstructor.statusState.workerAssigned","已分配工人");
        add("gui.neosim.BuildingConstructor.statusState.loading","加载蓝图");
        add("gui.neosim.BuildingConstructor.statusState.waiting","等待资源");
        add("gui.neosim.BuildingConstructor.statusState.building","建造中");
        add("gui.neosim.BuildingConstructor.statusState.complete","已完成");
        add("gui.neosim.BuildingConstructor.builderLevel","建造者 Lv.%s");
        add("gui.neosim.BuildingConstructor.soulOut","灵魂出窍");
        add("gui.neosim.BuildingConstructor.adjustUp","上升");
        add("gui.neosim.BuildingConstructor.adjustDown","下降");
        add("gui.neosim.BuildingConstructor.adjustMirror","镜像");
        add("gui.neosim.BuildingConstructor.adjustRotate","旋转");
        add("gui.neosim.BuildingConstructor.dirNorth","N");
        add("gui.neosim.BuildingConstructor.dirSouth","S");
        add("gui.neosim.BuildingConstructor.dirWest","W");
        add("gui.neosim.BuildingConstructor.dirEast","E");
        add("gui.neosim.BuildingConstructor.searchModeBuilding","建筑");
        add("gui.neosim.BuildingConstructor.searchModeAuthor","作者");
        add("gui.neosim.BuildingConstructor.filterSpecific","特定格式");
        add("gui.neosim.BuildingConstructor.filterAll","全部格式");
        add("gui.neosim.BuildingConstructor.filterTxt","旧格式");
        add("gui.neosim.BuildingConstructor.filterLitematic","新格式");

        add("gui.neosim.ControlBox.title","控制箱");
        add("gui.neosim.ControlBox.building","建筑: %s");
        add("gui.neosim.ControlBox.author","作者: %s");
        add("gui.neosim.ControlBox.placer","所建玩家: %s");
        add("gui.neosim.ControlBox.residents","居民: %s");
        add("gui.neosim.ControlBox.none","无");
        add("gui.neosim.ControlBox.noRecord","无此建筑记录");
        add("gui.neosim.ControlBox.close","关闭");

        add("entity.neo_sim.nsnpc","新模拟城市NPC");

        add("gui.neosim.npc.title","NPC");
        add("gui.neosim.npc.setSkin","设置皮肤");
        add("gui.neosim.npc.rename","重命名");
        add("gui.neosim.npc.rename.surname","姓");
        add("gui.neosim.npc.rename.givenName","名");
        add("gui.neosim.npc.rename.confirm","确认");
        add("gui.neosim.npc.rename.cancel","取消");
        add("gui.neosim.npc.back","返回");
        add("gui.neosim.npc.info.sex","性别: %s");
        add("gui.neosim.npc.info.male","男");
        add("gui.neosim.npc.info.female","女");
        add("gui.neosim.npc.info.city","城市: %s");
        add("gui.neosim.npc.info.noCity","无");
        add("gui.neosim.npc.info.age","年龄: %d");
        add("gui.neosim.npc.info.home","家: %s");
        add("gui.neosim.npc.info.noHome","无");
        add("gui.neosim.npc.skin.prevPage","上一页");
        add("gui.neosim.npc.skin.nextPage","下一页");
        add("gui.neosim.npc.skin.openFolder","添加自定义皮肤");
        add("gui.neosim.npc.skin.searchPlayer","输入玩家名");
        add("gui.neosim.npc.skin.searchConfirm","确定");
        add("gui.neosim.npc.skin.searching","正在搜索...");
        add("gui.neosim.npc.skin.searchFailed","失败");
        add("gui.neosim.npc.info.relationship","关系: %s");
        add("gui.neosim.npc.info.single","单身");
        add("gui.neosim.npc.info.livingWithSomeone","与他人同居");
        add("gui.neosim.npc.family.open","族谱");
        add("gui.neosim.npc.family.title","族谱：%s");
        add("gui.neosim.npc.family.father","父亲");
        add("gui.neosim.npc.family.mother","母亲");
        add("gui.neosim.npc.family.son","儿子");
        add("gui.neosim.npc.family.daughter","女儿");
        add("gui.neosim.npc.family.brother","兄弟");
        add("gui.neosim.npc.family.sister","姐妹");
        add("gui.neosim.npc.family.grandfather","祖父");
        add("gui.neosim.npc.family.grandmother","祖母");
        add("gui.neosim.npc.family.partner","配偶");
        add("gui.neosim.npc.family.noParents","父母：无");
        add("gui.neosim.npc.family.noPartner","配偶：无");
        add("gui.neosim.npc.family.noChildren","子女：无");
        add("gui.neosim.npc.family.noSiblings","兄弟姐妹：无");
        add("gui.neosim.npc.family.noGrandparents","祖父母：无");

        add("config.neosim.initialCredit","初始信用点");
        add("config.neosim.initialCredit.tooltip","城市的初始信用点");
        add("config.neosim.creditsPerBlock","每方块信用点");
        add("config.neosim.creditsPerBlock.tooltip","每放置一个方块扣除的信用点");
        add("config.neosim.maxPopulation","最大人口数");
        add("config.neosim.maxPopulation.tooltip","城市的最大人口数");
        add("config.neosim.npcMinAge","NPC最小年龄");
        add("config.neosim.npcMinAge.tooltip","NPC的最小随机年龄");
        add("config.neosim.npcMaxAge","NPC最大年龄");
        add("config.neosim.npcMaxAge.tooltip","NPC的最大随机年龄");
        add("config.neosim.lifeRentDefault","住宅默认租金");
        add("config.neosim.lifeRentDefault.tooltip","每天每座有居民的住宅收取的租金，未按体积定价的记录使用此默认值");
        add("config.neosim.lifeRentPerBlock","按建筑体积定价系数");
        add("config.neosim.lifeRentPerBlock.tooltip","完工住宅按非空气方块数×该系数计算每日租金");
        add("config.neosim.lifeAdultAge","成年年龄");
        add("config.neosim.lifeAdultAge.tooltip","居民长到该年龄即成年：可被雇佣，跨过该年龄当天退父母家并开始找房子");
        add("config.neosim.lifeMaxAge","寿终年龄");
        add("config.neosim.lifeMaxAge.tooltip","超过该年龄后，居民每天有1/10概率自然寿终");
        add("config.neosim.lifeAgingAdultDay","成人每周长岁日");
        add("config.neosim.lifeAgingAdultDay.tooltip","成人每周长岁的星期");
        add("config.neosim.lifeAgingChildDays","儿童每周长岁日");
        add("config.neosim.lifeAgingChildDays.tooltip","儿童每周长岁的星期列表");
        add("config.neosim.lifeGenealogyDepth","族谱血亲回溯深度");
        add("config.neosim.lifeGenealogyDepth.tooltip","族谱血亲判定向上回溯的最大代数");
        add("config.neosim.lifeMarriageChance","结婚概率");
        add("config.neosim.lifeMarriageChance.tooltip","BESTFRIENDS满级时掷硬币结婚的概率");
        add("config.neosim.lifePregnancyDays","孕期天数");
        add("config.neosim.lifePregnancyDays.tooltip","从怀孕到分娩的天数");
        add("config.neosim.lifePregnancyChance","怀孕概率");
        add("config.neosim.lifePregnancyChance.tooltip","怀孕概率（1/7）");
        add("config.neosim.lifeRestChance","居家休息概率");
        add("config.neosim.lifeRestChance.tooltip","有家无业市民白天在家休息、不外出社交的概率");
        add("config.neosim.lifePregnancyMaxAge","受孕上限年龄");
        add("config.neosim.lifePregnancyMaxAge.tooltip","女性超过该年龄后不再参与受孕");
        add("config.neosim.lifePregnancyStartStage","受孕初始孕期进度");
        add("config.neosim.lifePregnancyStartStage.tooltip","受孕瞬间孕期进度的初始值，越高则总孕期越短");
        add("config.neosim.lifeSocialRange","社交寻找半径");
        add("config.neosim.lifeSocialRange.tooltip","无业市民白天寻找社交对象的最大距离（格）");
        add("config.neosim.lifeSocialArriveDist","社交判定范围");
        add("config.neosim.lifeSocialArriveDist.tooltip","两人相距达到该值（格）即视为到达、开始凑在一起聊天");
        add("config.neosim.lifeRelationshipDowngradeChance","关系变差概率");
        add("config.neosim.lifeRelationshipDowngradeChance.tooltip","每次社交结算时关系下降而非上升的概率");
        add("config.neosim.lifeRelationshipChangeMax","单次关系增减量上限");
        add("config.neosim.lifeRelationshipChangeMax.tooltip","每次社交结算时关系增减幅度的最大值");
        add("config.neosim.lifeMarriageSubLevel","结婚所需关系度");
        add("config.neosim.lifeMarriageSubLevel.tooltip","BESTFRIENDS 关系达到该子等级后才会触发结婚判定");

        // NeoForge 配置界面（ConfigurationScreen）分类/按钮/标题翻译
        add("neo_sim.configuration.title","%s 配置");
        add("neo_sim.configuration.section.neo.sim.toml.title","%s 通用配置");
        add("neo_sim.configuration.section.neo.sim.toml","%s 配置");
        add("neo_sim.configuration.general","通用");
        add("neo_sim.configuration.general.button","通用");
        add("neo_sim.configuration.general.tooltip","城市初始资金、建造费用、人口上限与 NPC 年龄范围");
        add("neo_sim.configuration.life","生活系统");
        add("neo_sim.configuration.life.button","生活系统");
        add("neo_sim.configuration.life.tooltip","居民生命周期相关参数：房租、衰老、作息、生育、社交、关系与婚姻");
        add("neo_sim.configuration.rent","房租与收入");
        add("neo_sim.configuration.rent.button","房租与收入");
        add("neo_sim.configuration.rent.tooltip","住宅每日收租的默认值与按建筑体积定价系数");
        add("neo_sim.configuration.aging","衰老与寿终");
        add("neo_sim.configuration.aging.button","衰老与寿终");
        add("neo_sim.configuration.aging.tooltip","成年年龄、寿终年龄与每周长岁日");
        add("neo_sim.configuration.genealogy","族谱");
        add("neo_sim.configuration.genealogy.button","族谱");
        add("neo_sim.configuration.genealogy.tooltip","族谱血亲回溯深度");
        add("neo_sim.configuration.rest","作息");
        add("neo_sim.configuration.rest.button","作息");
        add("neo_sim.configuration.rest.tooltip","有家无业市民白天居家休息概率");
        add("neo_sim.configuration.reproduction","生育与分娩");
        add("neo_sim.configuration.reproduction.button","生育与分娩");
        add("neo_sim.configuration.reproduction.tooltip","孕期天数、怀孕概率、受孕上限年龄与初始孕期进度");
        add("neo_sim.configuration.social","社交与串门");
        add("neo_sim.configuration.social.button","社交与串门");
        add("neo_sim.configuration.social.tooltip","无业市民白天社交的寻找半径与到达判定距离");
        add("neo_sim.configuration.relationship","关系增减");
        add("neo_sim.configuration.relationship.button","关系增减");
        add("neo_sim.configuration.relationship.tooltip","每次社交结算时关系变差概率与增减量上限");
        add("neo_sim.configuration.marriage","婚姻");
        add("neo_sim.configuration.marriage.button","婚姻");
        add("neo_sim.configuration.marriage.tooltip","结婚概率与结婚所需关系度");

        add("gui.neosim.npc.info.maternityLeave","产假中");
    }
}
